pkg/minikube/cluster/commands.go

@jstrachan Will release after this is merged.

Add CORS flag to OpenShift invocation

---

cmd/minikube/cmd/start.go
pkg/minikube/cluster/cluster.go
pkg/minikube/cluster/cluster_test.go
pkg/minikube/cluster/commands.go

Set router subdomain to <ip>.xip.io by default

---

README.md
cmd/minikube/cmd/console.go
docs/minishift.md
docs/minishift_console.md
docs/minishift_logs.md
docs/minishift_version.md
pkg/minikube/cluster/cluster.go
pkg/minikube/cluster/cluster_test.go

Rename dashboard command to console

---

Godeps/Godeps.json
vendor/k8s.io/kubernetes/pkg/api/validation/validation.go
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/deep_copy_generated.go
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/types.generated.go
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/types.go
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/conversion_generated.go
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/deep_copy_generated.go
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/defaults.go
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/types.go
vendor/k8s.io/kubernetes/pkg/version/base.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jimmidyson/minishift/37)

Uprade to Kubernetes v1.3.3

---

cmd/minikube/cmd/start.go
docs/minishift_start.md
pkg/minikube/cluster/cluster.go

--internal-registry=true --router=true

Fixes #39: You can use minishift start

---

Makefile
pkg/minikube/cluster/commands.go

Ensure public master address uses routable IP

---

Makefile

make install, will install minishift to $GOPATH/bin

Support: make install

---

pkg/minikube/update/update.go

@jimmidyson not sure if this is the best approach but; I've vendored the minishift update.go package in gofabric8 and reused the `MaybeUpdate`  function which works great now that gofabric8 releases are in the same form as minikube and minishift!  - by "the same form" I mean they have a checksum and are not tarballs.
I've also tested `update.MaybeUpdateFromGithub(os.Stdout)` which still works to update minishift as the default.
I had to make these small changes so that the update function is generic enough for both gofabric8 and minishift.
I wasn't sure if vendoring this package is the correct way or if we should split out the update into its  own repo but figured I'd start here as it was easier and it works.
Let me know what you think.

make update feature generic so it can be reused

---

pkg/minikube/update/update.go

Fixes #73
How does that look @davsclaus?

Show current version in update prompt

---

pkg/minikube/cluster/cluster.go

Fixes #76 - thanks for the suggestion @davsclaus!

Support Kubernetes service annotations

---

pkg/minikube/update/update.go

@jimmidyson I missed this one, it should be the last!

allow the latest version to be passed in

---

README.md

* Fixed formatting issue introduced by commit [`3672d25d97addee41f43cb57fadbd50bd2f98716`](https://github.com/jimmidyson/minishift/commit/3672d25d97addee41f43cb57fadbd50bd2f98716
)

Fixed README broken link and formatting

---

cmd/minikube/cmd/start.go
docs/minishift_start.md
pkg/minikube/cluster/cluster.go

As discussed on IRC with @budhrg

Enable docker registry by default & ensure docker-registry service has a node port.

---

pkg/minikube/update/update.go

Fix up update logic to ensure binary is properly updated

---

docs/docker-machine-drivers.md
docs/troubleshooting.md

This patch will add xhyve driver required version, manual installation steps and troubleshoot steps.

Issue #214 Document xhyve driver known issues

---

README.md
docs/docker-machine-drivers.md

Following up on pull request #240 adressing issue #203

Issue #203 Documentation updates

---

README.md
circle.yml

This will enable OS-X build on circle-ci. This PR is still under test.

Issue #212 Add circle-ci to enable OS-X builds

---

pkg/minishift/provisioner/minishift_provisioner_test.go
pkg/minishift/provisioner/utils.go

This patch will add selinux label to our custom provisioner.

Issue #280 Add selinux flag to custom provisioner

---

cmd/minikube/cmd/start.go

Issue #289 Remove duplicate message of cluster up during minishift start

---

pkg/minishift/provisioner/utils.go

This patch adds addition options which required for latest docker for RHEL.

Issue #308 Update needed for rhel custom provisioner to accommodate changes for latest docker

---

centos_ci.sh

Issue #173 Setup CI build on CentOS CI

---

README.md

Issue #313 Add build status of CentOS CI in README

---

Makefile
docs/minishift_start.md

Issue #328 Upgrade to Openshift 1.4.1

---

centos_ci.sh

Issue #362 Add GH_TOKEN into centos_ci script to be used by CI

---

Makefile
cmd/minikube/cmd/config/config_test.go
cmd/minikube/cmd/config/set_test.go
cmd/minikube/cmd/config/validations_test.go
cmd/minikube/cmd/console_test.go
cmd/minikube/cmd/start_test.go
pkg/minikube/cluster/cluster_test.go
pkg/minikube/cluster/cluster_windows_test.go
pkg/minikube/constants/constants_test.go
pkg/minishift/cache/oc_caching_test.go
pkg/minishift/provisioner/minishift_detector_test.go
pkg/minishift/provisioner/minishift_provisioner_test.go
pkg/minishift/registration/redhat_test.go
pkg/minishift/util/oc_parse_test.go
pkg/testing/cli/viper.go
pkg/util/github/github_test.go
pkg/util/utils_test.go
test/integration/flags.go
test/integration/setup.go
test/integration/ssh_test.go
test/integration/start_docker_env_test.go
test/integration/start_stop_delete_test.go
test/integration/util/util.go

Issue #371 Fixing fmt and fmtcheck targets

---

README.md
ROADMAP.md

Addressing issue #207 - Adding a high level roadmap

Issue #207 Adding ROADMAP.md

---

README.md

Issue #413 Update irc name in README

---

hack/boilerplate/boilerplate.py
pkg/minishift/clusterup/dockerhost.go

Issue #420 Adding year 2017 to boilerplate.py

---

centos_ci.sh

Issue #435 Enable CI to get triggered when a push to master occurs

---

docs/minishift_start.md

Issue #454 Adding the missing docs change

---

pkg/minishift/registration/redhat.go

Issue #468 Fixing the code to call registration with or without proxy config

---

cmd/minishift/cmd/delete.go
cmd/minishift/cmd/root.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/stop.go
docs/minishift.md
docs/minishift_config.md
docs/minishift_config_get.md
docs/minishift_config_set.md
docs/minishift_config_unset.md
docs/minishift_config_view.md
docs/minishift_console.md
docs/minishift_delete.md
docs/minishift_docker-env.md
docs/minishift_get-openshift-versions.md
docs/minishift_ip.md
docs/minishift_logs.md
docs/minishift_openshift.md
docs/minishift_openshift_config.md
docs/minishift_openshift_config_set.md
docs/minishift_openshift_config_view.md
docs/minishift_openshift_restart.md
docs/minishift_service.md
docs/minishift_service_list.md
docs/minishift_ssh.md
docs/minishift_start.md
docs/minishift_status.md
docs/minishift_stop.md
docs/minishift_version.md

Fix #432 This patch is mostly a refactor of what we had in past.

Issue #432 Flags --username and --password should not be placed with common flags

---

README.md

Minor typo which will fix broken link in ReadMe

Issue #507 Interacting with OpenShift link is broken in the ReadMe

---

Makefile
docs/minishift_start.md

Issue #538 Upgrade to minishift-b2d ISO v1.0.2

---

README.md

Also, updated link for Hyper-V in the 'Prerequisites section' to point to - installation of Hyper-V on windows 10 and moved the sentence above the 'Important section' to the first paragraph in the Prerequisites section, to ensure better visibility to the points listed under Important.

Issue #265 Adding note for virtual switch creation for Hyper-V.

---

pkg/minishift/provisioner/utils.go

This patch need testing against latest build of centos which can be get from http://artifacts.ci.centos.org/minishift/minishift-centos-iso/pr/112/  Once I test it through will remove 'wip' flag.
Addresses issue #588

Issue #588 Port mapping doesn't seem to work

---

docs/Rakefile
docs/source/_topic_map.yml
docs/source/developing/ci.adoc
docs/source/developing/developing.adoc
docs/source/developing/index.adoc
docs/source/developing/releasing.adoc
docs/source/developing/writing-docs.adoc
docs/source/index.adoc

Issue #596 Adjusting headers of generated adoc files and updates to site

---

Makefile

Issue #629 Upgrading to OpenShift version v1.5.0-rc.0

---

docs/source/_topic_map.yml

Issue #658 Fix broken links in 'Developing Minishift' overview page

---

README.md

Fix the https://github.com/minishift/minishift/issues/668

Issue #668 Wrong URL of minishift start command reference in file "README.md".

---

README.adoc
docs/source/getting-started/installing.adoc

Fixes #689 
This PR updates the text in the hypervisor prerequisites to reflect how the VM and OpenShift interact, per @LalatenduMohanty feedback on PR #624 .

Issue #689 Fix text about vm that provisions openshift

---

appveyor.yml

Issue #703 Fixing version of Glide for AppVeyor build

---

Makefile
centos_ci.sh

Issue #535 CentOS CI changes for docs artifacts uploads

---

centos_ci.sh

Issue #716 Update CI master code to host the docs in artifacts server

---

cmd/minishift/cmd/addon/addon_disable.go
cmd/minishift/cmd/addon/addon_enable.go
cmd/minishift/cmd/addon/addon_install.go

Issue #652 Printing messages for addons enable and disable

---

addons/fuse-templates/fis-image-streams.json
addons/fuse-templates/fuse-templates.addon
addons/fuse-templates/karaf2-camel-amq-template.json
addons/fuse-templates/karaf2-camel-log-template.json
addons/fuse-templates/karaf2-camel-rest-sql-template.json
addons/fuse-templates/karaf2-cxf-rest-template.json
addons/fuse-templates/spring-boot-camel-amq-template.json
addons/fuse-templates/spring-boot-camel-config-template.json
addons/fuse-templates/spring-boot-camel-drools-template.json
addons/fuse-templates/spring-boot-camel-infinispan-template.json
addons/fuse-templates/spring-boot-camel-rest-sql-template.json
addons/fuse-templates/spring-boot-camel-teiid-template.json
addons/fuse-templates/spring-boot-camel-template.json
addons/fuse-templates/spring-boot-camel-xml-template.json
addons/fuse-templates/spring-boot-cxf-jaxrs-template.json
addons/fuse-templates/spring-boot-cxf-jaxws-template.json
pkg/minishift/addon/manager/addon_manager_test.go

@LalatenduMohanty Please test it out and also ask fuse folks to test it out.

Issue #775 Add Fuse templates and imagestream

---

Makefile

Issue #784 Fix 'make release' target for file extension change

---

docs/source/using/accessing-the-openshift-docker-registry.adoc

Issue #792 Fix broken link in openshift registry doc

---

docs/source/_topic_map.yml

Fix #799 
Sending the PR based on the comment https://github.com/minishift/minishift/issues/799#issue-223339324

Issue #799 Sync the order of links in 'Getting Started' page

---

circle.yml

This patch will have glide specific tag for circle CI.

Issue #571 Add glide specific tag 0.12.3 for circle CI

---

cmd/minishift/cmd/env.go
cmd/minishift/cmd/oc_env.go
cmd/minishift/cmd/oc_env_test.go
cmd/minishift/cmd/oc_env_test_windows.go
cmd/minishift/cmd/openshift/config.go
cmd/minishift/cmd/openshift/openshift.go
cmd/minishift/cmd/openshift/registry.go
cmd/minishift/cmd/openshift/restart.go
cmd/minishift/cmd/openshift/service.go
cmd/minishift/cmd/openshift/version.go
cmd/minishift/cmd/root.go
docs/source/getting-started/quickstart.adoc
docs/source/using/docker-daemon.adoc
docs/source/using/interacting-with-openshift.adoc
pkg/util/shell/shell.go
test/integration/features/basic.feature

Issue #142 Introduce oc-env command

---

Makefile

Issue #544 Using grep instead of read in fmtcheck target

---

ROADMAP.adoc

Issue #848 Updating and syncing  ROADMAP

---

docs/source/developing/developing.adoc

Issue #643 Adding link to Minishift docs on godoc.org

---

docs/source/developing/releasing.adoc

Issue #897 Commit message starting with lowercase for release

---

docs/source/getting-started/installing.adoc
docs/source/getting-started/uninstalling.adoc

Fix #902 
@hferentschik Could we merged so that it is available in the next doc sync with docs.openshift.org ?

Issue #902 Fix the links in installation and installation guide

---

Makefile

Issue #909 Upgrade OpenShift origin verstion to 1.5.1

---

cmd/minishift/cmd/start.go

This will fix unwanted message from chcon/restorecon which coming due to registry directory doesn't have permission for modify.

Issue #916 Exclude registry directory from chcon/restorecon list

---

pkg/minishift/provisioner/minishift_provisioner.go

Issue #912 Resolve error when no SSH installed on Windows

---

docs/source/using/troubleshooting.adoc
pkg/minishift/registration/redhat.go
pkg/util/utils.go
pkg/util/utils_test.go

I hope this will patch up all special character war in password string.

Issue #939 Add method to handle single quote string to password

---

cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_test.go
docs/source/using/managing-minishift.adoc
pkg/minikube/cluster/cluster.go
pkg/minishift/cache/oc_caching.go
pkg/minishift/cache/oc_caching_test.go
pkg/util/github/github.go
pkg/util/github/github_test.go
pkg/util/proxy.go
pkg/util/proxy_test.go
pkg/util/utils.go
pkg/util/utils_test.go

This reverts d28820858. Before merging this, we should probably make sure that an alternative approach works, but otherwise I suggest to reopen issue #718, apply this patch to revert the changes and then implement a different solution.

Issue #718 Creating explicit struct for dealing with proxy settings

---

cmd/minishift/cmd/addon/addon.go
cmd/minishift/cmd/addon/addon_apply.go
cmd/minishift/cmd/addon/addon_apply_test.go
cmd/minishift/cmd/addon/addon_enable.go
cmd/minishift/cmd/env.go
cmd/minishift/cmd/hostfolder/mount.go
cmd/minishift/cmd/hostfolder/umount.go
cmd/minishift/cmd/openshift/registry.go
cmd/minishift/cmd/util/util.go
docs/source/using/addons.adoc
pkg/minishift/addon/manager/addon_manager.go

Issue #637 Adding a new addon sub-command "apply"

---

cmd/minishift/cmd/start.go
pkg/minishift/clusterup/clusterup.go
pkg/minishift/clusterup/clusterup_test.go

- Added more concise error message for the case that unparsable version gets specified
- Updated tests
Addresses #410

Issue #410 Allow OpenShift version to be specified without 'v' prefix

---

pkg/minikube/cluster/cluster.go

Issue #1005 Interactive SSH

---

docs/source/using/managing-minishift.adoc

Fixes issue #919 
This PR supercedes PR #1001 and is adjusted for the updated issue description. 
Note: We are still missing an example for a sub-command, I asked for this in the other PR but the discussion changed focus so now please provide an example that would reflect some real-life use case that we can show to the readers.

Issue #919 document SSH usage

---

docs/source/developing/writing-docs.adoc

Fixes issue #618 
This PR supersedes previous PR #836 and includes all the feedback cycles from the team and the latest patch from @hferentschik.

Issue #618 Update "writing and publishing docs" topic

---

pkg/minikube/kubeconfig/config.go

Issue #1011 Fix Adding developer to sudoers when use v1.3.6

---

docs/source/getting-started/setting-up-driver-plugin.adoc

Issue #1051 explicitly mention External in Hyper-V setup documentation

---

pkg/minikube/kubeconfig/config.go
pkg/minikube/kubeconfig/config_test.go
pkg/minishift/clusterup/clusterup.go

Issue #1011 Fix Adding developer to sudoers when using OpenShift 3.6.x

---

glide.lock
glide.yaml
pkg/minishift/docker/image/image_handler.go
pkg/minishift/registration/redhat.go
pkg/util/utils.go
pkg/util/utils_test.go

Fix #1036 
Not fixing #1054 as part of this PR as I feel we might have to investigate more on the ways we get timeout and handle that as part of that issue.

Issue #1036 Add spinning wheel during registration process

---

pkg/minishift/addon/command/echo_command.go
pkg/minishift/addon/command/echo_command_test.go

Issue #1064 Fixed the echo add-on command to print empty line

---

Makefile
cmd/minishift/cmd/start_test.go
cmd/minishift/cmd/version.go
cmd/minishift/cmd/version_test.go
pkg/version/version.go

- Adding test ensuring Minishift vcersion format
- Using Tee in console_test and making sure that Stdout is properly reset
- Clenaing up start_test.go

Issue #515 Adding commit sha to version string

---

Makefile

cut v1.3.0

---

docs/source/openshift/openshift-client-binary.adoc

Reference oc usage and authentication concept to the latest OpenShift doc.

Issue #1148 Reference the latest OpenShift doc

---

docs/source/contributing/ci.adoc
docs/source/getting-started/installing.adoc
docs/source/getting-started/setting-up-driver-plugin.adoc
docs/source/openshift/exposing-services.adoc
docs/source/openshift/openshift-client-binary.adoc
docs/source/openshift/openshift-docker-registry.adoc
docs/source/using/addons.adoc
docs/source/using/host-folders.adoc
docs/source/using/managing-minishift.adoc
docs/source/using/troubleshooting.adoc

Fixes #1164 Correct duplicate IDs in AsciiDoc sources

Fixes #1164 Correct duplicate IDs in AsciiDoc sources

---

pkg/minishift/clusterup/clusterup.go

Issue #1169 Return error when oc cluster up flag is not supported

---

Makefile

We should wait till we have new release in place from ISO side.

Issue #1177 Update to latest CentOS ISO version

---

Makefile

Cut v1.3.1

---

cmd/minishift/cmd/start.go

Issue #1193 Add fix to use insecure registry with start command

---

cmd/minishift/cmd/console.go

Issue #567 Add request-token flag to console command to request an API token

---

Makefile
docs/source/contributing/releasing.adoc

Issue #657 Replacing gnutar with tar in release target

---

pkg/minishift/hostfolder/hostfolder.go
pkg/minishift/util/hostip.go
pkg/util/input.go

Issue #1223 Refactor printxx() to fmt.Printxx()

---

cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_test.go
cmd/minishift/cmd/util/shared_flags.go

Issue #1176 Handle slice variables explicitly in start command

---

Makefile

Issue #484 Update b2d iso version to add nfs support

---

cmd/minishift/cmd/delete.go
cmd/minishift/cmd/registration.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/stop.go
pkg/minikube/cluster/cluster.go
pkg/minikube/cluster/credentials.go
pkg/minishift/cluster/registration.go
pkg/minishift/registration/redhat.go
pkg/minishift/registration/utils.go
pkg/util/input.go
pkg/util/utils.go

Fixes #1200 
```
$ minishift start --iso-url centos
$ minishift ssh "sudo systemctl stop sshd"
$ minishift stop
Stopping local OpenShift cluster...
Error unregistering the VM: ssh command error:
command : sudo cat /etc/os-release
err     : exit status 255
output  : 
```
```
$ minishift start --iso-url centos
$ minishift ssh "sudo systemctl stop sshd"
$ minishift delete
Deleting the Minishift VM...
Minishift VM deleted.
```

Issue #1200 Refactor registration code

---

Makefile
centos_ci.sh

Issue #1235 Fix issues with CI release job

---

.travis.yml
appveyor.yml
circle.yml

Issue #1241 Use 'make prerelease' target

---

cmd/minishift/cmd/root.go

Issue #1203 Install default add-ons if addons directory is not present

---

cmd/minishift/cmd/openshift/registry.go
cmd/minishift/cmd/util/util.go
pkg/minishift/addon/command/openshift_command.go
pkg/minishift/constants/constants.go
pkg/minishift/openshift/openshift.go
pkg/minishift/openshift/registry.go
test/integration/features/basic.feature

Issue #1147 Add registry add-on as part of default

---

scripts/planning/sprint-planning.sh

Addresses #1292 
In preparation of next sprint planning

Issue #1292 Adding two more estimation columns to planning script

---

docs/source/getting-started/installing.adoc

Fix #1329 
@praveenkumar @LalatenduMohanty Please verify following command at your end
```
$ brew cask install --force minishift
```

Issue #1329 Remove outdated doc on installing minishift beta in macOS

---

cmd/minishift/cmd/start_preflight.go

Issue #1296 Fix preflight check for kvm driver

---

cmd/minishift/cmd/root.go
cmd/minishift/cmd/start.go
glide.lock
glide.yaml
pkg/minikube/cluster/cluster.go
pkg/minishift/provisioner/minishift_provisioner.go
pkg/minishift/registration/redhat.go
pkg/minishift/registration/utils.go
pkg/util/utils.go

Fix #1277  and #1339 .
```
$ minishift start
-- Installing default add-ons ... OK
[...]
Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.1.0/minishift-b2d.iso'
40.00 MiB / 40.00 MiB [==========================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ... OK
[...]
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
12.04 MiB / 34.72 MiB [=====================================================>---------------------------------------------------------------------------------------------------]  34.69% 24s^C
$ MINISHIFT_NO_PROGRESSBAR=y minishift start
-- Installing default add-ons ... OK
[...]
Downloading ISO …
```

Issue #1277 and #1339 Add no progress bar flag and fix spinning wheel

---

cmd/minishift/cmd/start_preflight.go
glide.lock
glide.yaml
pkg/minishift/shell/powershell/powershell.go

Fixes #1368 
Needed for Hyper-V preflight check and static IP address...

Add PowerShell wrapper and check if Hyper-V installed

---

cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_test.go

Fix #1363 
Previously #1387, but i did force push on that branch because a build was failing, so that PR got closed automatically, Sorry for the mess!

Issue #1363 Fix iso-url to work with case sensitive urls.

---

pkg/util/progressdots/progressdots.go

- Replaced bool with type struct{} signature which require no memory allocation ( https://dave.cheney.net/2014/03/25/the-empty-struct )
- Close the channel when Stop

Issue #1374 Append extra second to progress dot

---

centos_ci.sh
test/integration/features/profile.feature

Issue #1407 Making profile tests part of integration tests

---

centos_ci.sh

Issue #1209 #1421 Add latest build and stop saving openshift docs

---

pkg/minishift/registration/redhat.go

- Initialization of progressDot channel should be part of for loop

Issue #1450 RHSM registration fail when retry

---

cmd/minishift/cmd/root.go

Issue #1460 Move all instance config creation to PersistentPreRun 

---

cmd/minishift/cmd/root.go
cmd/minishift/cmd/start.go
test/integration/features/cmd-addons.feature

Issue #1342 Moving the default add-on installation to PersistentPreRun

---

cmd/minishift/cmd/start.go
docs/source/using/managing-minishift.adoc

Issue #1512 Adding Minikube ISO to usage and documentation

---

cmd/minishift/cmd/status.go

Issue #1524 Using constants.ProfileName to get the profile name

---

Makefile
centos_ci.sh

Fix #1279 
Previous PR https://github.com/minishift/minishift/pull/1459

Issue #1279 Reduce time used in CI by using a prebuilt docs generation image

---

test/integration/features/provision_earlier_version.feature

Issue #1544 Typo around provision_earlier_version.feature file

---

.github/stale.yml

We can add this and see how it works out...
Addresses issue #1323

Issue #1323 Enabling and configuring the stale probot

---

pkg/minishift/clusterup/clusterup.go

Fix #1554 
That was the regression, we did fix it as part of #916 but looks like forget again when did refactor.

Issue #1554 Fix restorecon failure with new persistent volume for registry

---

cmd/minishift/cmd/start.go
cmd/minishift/cmd/util/oc.go
pkg/minishift/openshift/registry.go
pkg/minishift/openshift/service.go
pkg/minishift/openshift/service_test.go
test/integration/features/profile.feature

Fix #1557 
Also fix `minishift openshift service` command whose root cause is same.

Issue #1557 Fix openshift registry command for profiles

---

test/integration/features/cmd-config.feature
test/integration/integration_test.go

Issue #1532 Add support for Minikube ISO into integration tests

---

cmd/minishift/cmd/start_preflight.go

Fixes #1541 
please verify on Windows, /cc @budhrg

Issue #1541 Use well-known security ID to prevent localization issues

---

cmd/minishift/cmd/profile/profile_set.go
test/integration/features/profile.feature

This issue was introduced in commit c2aeff6

Issue #1574 Fixing profile set to work always

---

CONTRIBUTING.adoc
Makefile
circle.yml
docs/source/contributing/developing.adoc

- Integrating validate_commits into Circle CI
Issue #1559

Issue #1559 Adding a commit message validation target

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_preflight.go
docs/source/using/managing-minishift.adoc
pkg/minishift/constants/constants.go

Issue #1397 Improve pre-flight check for ISO URL

---

docs/source/getting-started/installing.adoc

Updating installation page. Issue referred to in note has been resolved for almost 5 months #204

Issue #1611 Remove outdated installation note

---

docs/source/getting-started/updating.adoc

Issue #1595 added to docs update works from v1.5.0 onwards

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/start_preflight.go

Issue #1606 check for valid VM Driver during preflight

---

docs/source/getting-started/installing.adoc
docs/source/troubleshooting/troubleshooting-misc.adoc

Issue #1430 Document need to set HYPERV_VIRTUAL_SWITCH env variable

---

cmd/minishift/cmd/profile/profile_list.go

Issue #1633 Display sorted list in the output of profile list

---

docs/source/openshift/exposing-services.adoc

Issue #1651 Removing link to Ingress Ip in OpenShift docs

---

docs/source/_topic_map.yml
docs/source/using/index.adoc
docs/source/using/profiles.adoc

Issue #1485 Improving the profile documentation

---

cmd/minishift/cmd/start_preflight.go
cmd/minishift/cmd/util/env.go
cmd/minishift/cmd/util/env_test.go

Issue #1583 Fix localisation issue for active libvirt networks

---

ROADMAP.adoc

Issue #1504 Updating the Roadmap document

---

.gitignore
cmd/minishift/cmd/start_preflight_notwin_test.go
cmd/minishift/cmd/start_preflight_test.go
cmd/minishift/cmd/start_preflight_windows_test.go

Issue #1690 Test cleanup in pre-flight check

---

pkg/minishift/cache/oc_caching.go
pkg/minishift/cache/oc_caching_test.go

Issue #546 Adding OS type to oc cache path

---

Makefile
cmd/minishift/cmd/config/util_test.go
cmd/minishift/cmd/update_test.go
cmd/minishift/cmd/util/env_test.go
docs/source/contributing/developing.adoc
pkg/minikube/cluster/cluster.go
pkg/minikube/cluster/driver_options_test.go
pkg/minishift/addon/addon_meta_test.go
pkg/minishift/docker/image/image_handler_test.go
pkg/minishift/hostfolder/hostfolder.go
pkg/minishift/profile/profile_test.go
pkg/minishift/provisioner/minishift_detector.go
pkg/minishift/registration/redhat.go
pkg/util/archive/archive.go
pkg/util/cmd/split_args_test.go
pkg/util/github/github_test.go
pkg/util/strings/strings_test.go
pkg/util/utils.go
pkg/util/utils_test.go

Issue #1688 Introducing vet target and fixing any vet violations

---

docs/source/getting-started/setting-up-driver-plugin.adoc

Issue #1629 Documentation of steps for setting up kvm driver on arch linux

---

Makefile
centos_ci.sh
docs/source/contributing/developing.adoc
test/integration/features/addon-xpaas.feature

This test checks if templates added by xpaas addon are available and if they can be deployed successfully.

Issue #1498 Add integration test for deployment of EAP applications

---

docs/source/using/basic-usage.adoc

Issue #1682 Fix minishift architecture diagram integration docs.openshift.org

---

docs/source/getting-started/installing.adoc
docs/source/getting-started/setting-up-driver-plugin.adoc
docs/source/using/host-folders.adoc
pkg/minikube/cluster/cluster.go

Issue #1602 Remove vmware-fusion mention/support from documentation

---

cmd/minishift/cmd/start.go

Fixes  #1662
- Add profile line into start log

Issue #1662 Add profile line into start log

---

cmd/minishift/cmd/profile/profile_set.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/util/oc.go
cmd/minishift/cmd/util/util.go
test/integration/features/profile.feature

Issue #1591 Removing misleading  message when switching profiles

---

docs/source/getting-started/setting-up-driver-plugin.adoc

Issue #1725 update xhyve driver version to 0.3.3 in docs

---

docs/source/using/addons.adoc

Issue #1730 Fix less than symbol in docs in section `OpenShift Version Semantics`

---

docs/source/using/addons.adoc

Issue #1389 Listing available add-ons in docs

---

cmd/minishift/cmd/profile/profile.go
cmd/minishift/cmd/root.go
cmd/minishift/cmd/util/util.go
cmd/minishift/cmd/util/util_test.go
docs/source/using/profiles.adoc

Issue #1714 Profile name should be alpha-numeric

---

docs/source/using/profiles.adoc

Issue #1714 Fixing the profile doc

---

cmd/minishift/cmd/openshift/service.go

Issue #1740 Making --url --inbroswer mutually exclusive

---

centos_ci.sh

Issue #1790 Remove coolstore test from nightly job

---

.github/ISSUE_TEMPLATE.md

Fixes #1581
Opened PR for feedback...

Issue #1581 Add GitHub issue template

---

Makefile

Issue #1788 Fix commit message validation regex

---

docs/source/contributing/ci.adoc
docs/source/contributing/developing.adoc

Issue #1785 Document the availability of commit message validation

---

cmd/minishift/cmd/env.go

Issue #1655 Remove Docker API version info from docker-env command

---

cmd/minishift/cmd/addon/addon_disable.go
test/integration/features/cmd-addons.feature

Add message when trying to disable an already disabled addon and when trying to set as active an already active profile

Issue #1398 Add message when re-setting states for addons and profile

---

cmd/minishift/cmd/openshift/list_versions.go
cmd/minishift/cmd/start.go
pkg/minikube/constants/constants.go
pkg/minishift/clusterup/clusterup.go
pkg/minishift/clusterup/clusterup_test.go
pkg/minishift/openshift/version/openshift_versions.go
pkg/minishift/openshift/version/openshift_versions_test.go
test/integration/features/provision_earlier_version.feature
test/integration/features/provision_various_versions.feature

Issue #1417 Use 3.6.0 for versions < v3.7.0 

---

test/integration/features/cmd-version.feature

Issue #1829 Fix regex to test minishift version in integration test

---

centos_ci.sh

Issue #1568 - Add nightly tests with for Minikube and CentOS images

---

cmd/minishift/cmd/root.go
cmd/minishift/cmd/root_test.go
docs/source/using/profiles.adoc
test/integration/features/profile.feature

Issue #1695 Restrict profile set and start command to create profiles

---

cmd/minishift/cmd/start.go
pkg/minishift/hostfolder/hostfolder.go
pkg/minishift/registration/redhat.go
pkg/minishift/registration/redhat_test.go
pkg/minishift/registration/utils.go
pkg/util/input.go

Issue #1653 Password can not be entered when console/terminal lacks PTY support

---

cmd/minishift/cmd/root.go

Issue #1388 Adding Minishift version information to debug logs

---

addons/registry-route/registry-route.addon

Issue #1733 Improve UX for registry-route addon

---

docs/source/openshift/openshift-docker-registry.adoc

- oc run web --image internal_expose_registry/project/myweb fails to pull images from an exposed internal registry.

Issue #1615 Document update for internal registry image pull

---

cmd/minishift/cmd/env.go

Issue #1743 Fix wrong eval in docker-env

---

test/integration/features/addon-xpaas.feature
test/integration/features/basic.feature
test/integration/features/cmd-openshift.feature
test/integration/features/provision_earlier_version.feature
test/integration/features/proxy.feature
test/integration/integration_test.go

Issue #1816 - Add a retry logic to integration tests

---

pkg/minishift/clusterup/clusterup.go

Issue #1894 Increase timeout to 5 mins for PV creation

---

pkg/minishift/openshift/version/openshift_versions_test.go

Issue #1913 Adding unit test for GreaterOrEqualToBaseVersion

---

pkg/minishift/addon/manager/addon_manager.go
pkg/minishift/addon/manager/addon_manager_test.go

Fix #1900 
Critical fix for Che addon.
Now, able to remove addon properly.
```
$ cat ~/.minishift/addons/demoaddon/demoaddon.addon 
echo This is demo addon with variable FOO whose value is #{FOO}
$ cat ~/.minishift/addons/demoaddon/demoaddon.addon.remove 
echo Removing demo addon with variable FOO whose value is #{FOO}
$ minishift addons install demoaddon
Addon 'demoaddon' installed
$ minishift addons apply demoaddon
This is demo addon with variable FOO whose value is abc
$ minishift addons remove demoaddon
-- Removing addon 'demoaddon':
Removing demo addon with variable FOO whose value is abc
```

Issue #1900 Fix removing addon when specifying Required-Vars and Var-Defaults

---

pkg/minishift/profile/profile.go

Issue #1840 Ignore non-directory/hidden stuffs inside profiles directory

---

scripts/planning/sprint-planning.sh

Issue #1936 Adding Anjan and removing Hardy from the planning script

---

docs/source/using/addons.adoc

Issue #1948 Fix typo in dynamic addons topic in docs

---

pkg/minishift/addon/manager/addon_manager.go
pkg/minishift/addon/manager/addon_manager_test.go
test/testdata/testaddons/invalidaddon/invalidaddon.addon
test/testdata/testaddons/invalidaddon/invalidaddon.addon.remove
test/testdata/testaddons/testaddon/testaddon.addon
test/testdata/testaddons/testaddon/testaddon.addon.remove

Issue #1940 Add unit tests for addon apply/remove actions

---

docs/source/getting-started/installing.adoc

Issue #1923 Update installing doc for ssh binary in windows.

Issue #1923 update installing.adoc

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/root.go
cmd/minishift/cmd/start_preflight.go
pkg/minikube/constants/constants.go

Fixes #1963 
Also refactor `checkIPConnectivity(d)`, `checkHttpConnectivity(d)` to use the default value of config options `CheckNetworkPingHost` and `CheckNetworkHttpHost`

Issue #1963 refactor creatConfigSetting to set default value

---

pkg/minishift/config/validations.go
pkg/minishift/config/validations_test.go

fixes https://github.com/minishift/minishift/issues/1982

Issue #1982 fixed minikube iso-url validation

---

cmd/minishift/cmd/addon/addon.go
test/integration/features/cmd-addons.feature

Issue #1986 User friendly error message for *.addon.remove file

---

test/integration/features/cmd-profile.feature

Issue #2018 Update name profile.featute to cmd-profile.feature

---

cmd/minishift/cmd/openshift/restart.go
pkg/minishift/openshift/openshift.go
test/integration/features/cmd-openshift.feature

Issue #2012 Print OpenShift restart message post its restart operation

---

cmd/minishift/cmd/start_preflight.go

Potential fix for Hyper-V Admin group check (e.g. #1541)

Issue #2047 Hyper-V Admin group check

---

cmd/minishift/cmd/start_preflight.go
cmd/minishift/cmd/start_preflight_windows.go

Fixes #1376 
See [#1376/comment](https://github.com/minishift/minishift/issues/1376#issuecomment-363766107)

Issue #1376 Improve detection of Hyper-V and error msg when VirtualBox is used as the Hypervisor

---

cmd/minishift/cmd/console.go
cmd/minishift/cmd/ip.go
test/integration/features/basic.feature

Issue #1996 Check host status for console and IP command

---

docs/source/contributing/releasing.adoc
scripts/release/brew-cask.sh

Issue #1324 Shell script to update the brew cask file

---

cmd/minishift/cmd/completion.go

Issue #2080 Added RHEL and CenOS to CLI completion usage

---

pkg/minishift/update/update.go
pkg/util/utils.go
pkg/util/utils_test.go

Fix #2056 
Need to test in mac and Windows.

Issue #2056 Check writable permission before downloading during update

---

cmd/minishift/cmd/addon/addons_list.go
test/integration/features/basic.feature

Issue #1958 Fixing addon list display

---

addons/admin-user/admin-user.addon
addons/admin-user/admin-user.addon.remove
pkg/minishift/addon/parser/addon_parser_test.go

Issue #1919 Make admin-user addon as idempotent

---

cmd/minishift/cmd/config/config.go
pkg/minishift/config/validations.go
pkg/minishift/config/validations_test.go

Issue #2125 Validation for `hostfolders-sftp-port` config option

---

docs/source/troubleshooting/troubleshooting-getting-started.adoc

Issue #199 Adding Safari browser issue to troubleshooting

---

centos_ci.sh

Issue #2164 Enable SELinux for CentOS CI job

---

addons/registry-route/registry-route.addon
cmd/minishift/cmd/openshift/set.go
docs/source/using/addons.adoc
pkg/minishift/addon/command/openshift_command.go
pkg/minishift/constants/constants.go
pkg/minishift/openshift/openshift.go

Added WIP just to make sure we test it thoroughly with all the openshift versions.
Related to #2140

Issue #2140 Add entrypoint to run openshift command for origin container

---

pkg/minishift/update/update.go
pkg/util/utils.go

Fix #2189 
Test it as : 
```
$ make
$ minishift update
```

Issue #2189 Fix minishift update command

---

Makefile
pkg/minishift/openshift/version/openshift_versions_test.go

Issue #2183 Add GithubToken check to TestPrintUpStreamVersions

---

Gopkg.lock
Gopkg.toml
pkg/minikube/cluster/cluster_darwin.go

Before merge please test out artifact binary works as expected in the OSx with the hyperkit driver.

Issue #2185 Remove hyperkit dependency from Gopkg.toml

---

.gitlab-ci.yml
.travis.yml
appveyor.yml
centos_ci.sh
docs/source/contributing/developing.adoc

Issue #2198 Update dep version to v0.4.1

---

cmd/minishift/cmd/start_preflight.go

Issue #2121 override LANG env for default network preflight check

---

pkg/minishift/registration/redhat.go

Fixes: #2174 
Ref: https://issues.jboss.org/projects/CDK/issues/CDK-270

Issue #2174 Handle unregistration properly for rhel iso

---

docs/source/using/experimental-features.adoc

Fixes #2204 
Duplicate of #2205 on the right repo

Issue #2204 fixed IP only works with CentOS or RHEL ISO

---

cmd/minishift/cmd/start.go

Issue #2234 Move --logging and --metrics to be part of the experimental features

---

pkg/minishift/hostfolder/hostfolder_manager.go

How to test:
- Use minishift without this PR.
```
$ minishift hostfolder add test --type sshfs --source <your_source> --target /mnt/sda1/test
$ minishift hostfolder add test1 --type sshfs --source <your_source> --target /mnt/sda1/test1
$ ./minishift hostfolder list
Name    Type    Source                        Mountpoint        Mounted
test    sshfs   /home/prkumar/work/vagrant/   /mnt/sda1/test    N
test1   sshfs   /home/prkumar/work/vagrant/   /mnt/sda1/test1   N
$ ./minishift hostfolder mount test1
$ ./minishift hostfolder list
Name    Type    Source                        Mountpoint        Mounted
test    sshfs   /home/prkumar/work/vagrant/   /mnt/sda1/test    Y => we didn't mount it
test1   sshfs   /home/prkumar/work/vagrant/   /mnt/sda1/test1   Y
$ ./minishift hostfolder mount test …
```

Issue #2122 Add regex to determine a host folder is mounted

---

test/integration/features/addon-xpaas.feature

Issue #2133 Add test for EAP 7.1 template in addon-xpass.feature

---

cmd/minishift/cmd/update.go

Issue #1232 Add github and local file system location to review addon

---

pkg/minikube/assets/vm_assets.go
pkg/minishift/provisioner/buildroot_provisioner.go
pkg/minishift/provisioner/utils.go

Issue #2063 Fix cert permission for minikube ISO

---

test/integration/features/addon-registry-route.feature
test/integration/testsuite/minishift.go
test/integration/testsuite/testsuite.go
test/integration/util/shell.go
test/integration/util/util.go

Issue #1318 Integration test coverage for registry add-on

---

docs/source/openshift/exposing-services.adoc

Fix #2262   @gbraad hinted that I should document this.

Issue #2262 Add note about VirtualBox-based port forwarding

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/start.go

Fixes #273 Add experimental support to not provision the VM.

Issue #273 Do not provision the VM with OpenShift

---

pkg/minishift/openshift/version/openshift_versions.go
pkg/util/github/github.go

Issue #2242 show simple err msg for failed request to github

---

centos_ci.sh

Issue #2201 Fix CentOS CI job is failing in building docs

---

pkg/minishift/config/validations.go

Issue #1720 show error message that hyperv is not supported in windows7

---

test/integration/features/cmd-openshift.feature

Issue #1877 Nodejs-ex gets stuck on rollout during integration test

---

docs/source/using/basic-usage.adoc

Issue #2285 Update docs about lowercase proxy environment variables

---

cmd/minishift/cmd/hostfolder/sftpd.go
pkg/minishift/constants/constants.go
pkg/minishift/hostfolder/sshfs_hostfolder.go
pkg/util/filehelper/file.go

Fix #2123 
I hope integration test will be added as part of https://github.com/minishift/minishift/issues/2126.

Issue #2123 Key based authentication for sftpd server

---

docs/source/using/experimental-features.adoc

Issue #2309 Update documentation about service catalog

---

Makefile

Issue #2281 add target `assets` in Makefile

---

cmd/minishift/cmd/openshift/service.go
cmd/minishift/cmd/openshift/service_list.go
pkg/minishift/openshift/service.go
pkg/minishift/openshift/service_test.go
pkg/testing/testdata/testdata.go

Issue #1564 Print TLS service routes in o/p of `minishift openshift service list` command

---

cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_preflight.go

Issue #2284 Fix preflight messages around proxy env

---

pkg/util/proxy.go
pkg/util/proxy_test.go

Issue #2283 Fix special char handling in proxy

---

cmd/minishift/cmd/root.go
pkg/minishift/constants/constants.go
test/integration/features/cmd-profile.feature

Issue #2316 Don't create .minishift dir in version and completion commands

---

cmd/minishift/cmd/hostfolder/add.go

Issue #2219 Ask 'name' and 'type' for adding hostfolder interactively

---

test/integration/features/cmd-image.feature
test/integration/testsuite/minishift.go
test/integration/testsuite/testsuite.go

Issue #2335 - Define timeout of imageExportShouldComplete in feature

---

Makefile
test/integration/features/cmd-openshift.feature

Issue #2350 Update timeout of running integration test

---

docs/source/_topic_map.yml
docs/source/using/con_static-ip-overview.adoc
docs/source/using/experimental-features.adoc
docs/source/using/index.adoc
docs/source/using/static-ip.adoc

This commit also provides minor changes to **_using/experimental-features.adoc_** for consistency.

Issue #2323 Update Hyper-V static IP documentation

---

cmd/minishift/cmd/hostfolder/add.go
pkg/minishift/hostfolder/cifs_hostfolder.go
pkg/minishift/hostfolder/hostfolder_manager.go
pkg/minishift/hostfolder/sshfs_hostfolder.go

Issue #2345 Rename miniConfig to minishiftConfig

---

Makefile

Fixes #2342 
This reverts commit 88c983f1c9c6157abe7af98fbb2ab6ed135091a9 and
adds a new target "clean_bindata" to Makefile

Issue #2342 Removing the phony target assets in Makefile

---

cmd/minishift/cmd/status.go

Adds cache size to status. #1609

Issue #1609 Added Cache Size to Status

---

scripts/planning/sprint-planning.sh

Issue #2375 Fixing the sprint planning script for CDK milestones

---

Makefile
docs/source/contributing/developing.adoc
test/integration/features/basic.feature
test/integration/features/cmd-addons.feature
test/integration/features/cmd-config.feature
test/integration/features/cmd-image.feature
test/integration/features/provision-various-versions.feature
test/integration/testsuite/minishift.go
test/integration/testsuite/prepare.go
test/integration/testsuite/testsuite.go

Issue #2339 - Chdir to the test-dir as part of the beforeFeature()

---

test/integration/features/experimental-flags.feature
test/integration/testsuite/testsuite.go

Fix : #2322
Executed successfully on bash, powershell and command prompt 
How to test : 
```
make integration GODOG_OPTS="-tags experimental-feature"
```

Issue #2322 Add integration test step to test experimental feature

---

cmd/minishift/cmd/config/view.go

Issue #2321 Fix output of minishift config view

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/oc_env.go
cmd/minishift/cmd/preflight_artifacts.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_test.go
pkg/minikube/constants/constants.go
pkg/minishift/clusterup/clusterup.go
pkg/minishift/clusterup/clusterup_test.go
pkg/minishift/openshift/registry.go
test/integration/features/provision-various-versions.feature

Issue #2272 Remove older version support from minishift

---

cmd/minishift/cmd/config/functions.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_test.go
cmd/minishift/cmd/util/oc.go
pkg/minikube/kubeconfig/config.go
pkg/minishift/clusterup/clusterup.go
pkg/minishift/constants/constants.go
pkg/minishift/docker/docker.go
pkg/minishift/oc/oc.go

This still need some more work, atm I want to know integration tests status.

Issue #2377 use oc binary from the VM for cluster up

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_preflight.go
docs/source/getting-started/preparing-to-install.adoc
docs/source/getting-started/setting-up-virtualization-environment.adoc
docs/source/using/experimental-features.adoc
pkg/minikube/cluster/cluster.go
pkg/minikube/cluster/cluster_windows.go
pkg/minishift/config/validations_notwin.go
pkg/minishift/config/validations_windows.go
pkg/util/strings/strings.go

Fixes #2258 
Note: using same option names as minikube...

Issue #2258 Use config option for Virtual Switch

---

cmd/minishift/cmd/env.go
cmd/minishift/cmd/oc_env.go
pkg/util/shell/shell.go

I had a fairly involved test with a collegue and this seems to fix the problem well while also being not too bad of an OS-specific hack.

Issue #2413 Always emit uppercased NO_PROXY on Windows

---

addons/registry-route/registry-route.addon

This will also resolve the issue which I was seeing with oc-3.10.x, will rebase #2336 once this is merged.

Issue #2451 Remove older version support from registry-route addon

---

Gopkg.lock
Gopkg.toml
cmd/minishift/cmd/start_preflight.go
pkg/minishift/config/validations.go
pkg/minishift/config/validations_windows.go
pkg/minishift/network/settings_windows.go
pkg/minishift/shell/powershell/powershell.go

Fixes #2370
Tested with:
* static ip
* assign virtual switch (with modified `docker/machine` lib)
Untested:
* get network info from host
* ...

Issue #2370 allow non-ASCII for PowerShell, deprecates 3rd party library

---

cmd/minishift/cmd/root.go
cmd/minishift/cmd/start.go
pkg/minikube/constants/constants.go
pkg/minishift/clusterup/clusterup.go
pkg/minishift/constants/constants.go
pkg/minishift/docker/docker.go
pkg/minishift/oc/oc.go
pkg/minishift/openshift/openshift.go

Issue #2248 Changes to make run v3.10.0

---

Makefile

Issue #2467 Skipping the addon-xpaas  integration tests

---

cmd/minishift/cmd/start_preflight.go

Issue #2456 Fixed the typo in start_preflight.go.

---

docs/source/using/experimental-features.adoc
pkg/minishift/network/dns/localdns_darwin.go

Issue #2305 instructions for offline route access on macOS

---

cmd/minishift/cmd/start.go
cmd/minishift/cmd/util/util.go

Issue #2461 Genric: Add error msg in case required option not provided

---

cmd/minishift/cmd/hostfolder/add.go
docs/source/using/host-folders.adoc

Issue #2124 Make SSHFS as default hostfolder mount

---

addons/anyuid/anyuid.addon.remove
pkg/minishift/addon/parser/addon_parser_test.go

Issue #2514 Addon: added anyuid remove

---

test/integration/features/addon-registry-route.feature
test/integration/features/cmd-addons.feature

Issue #2518 Adding test for addon list --verbose

---

cmd/minishift/cmd/start_preflight.go

Issue  #2551 Fixing major typo in start_preflight.go

---

cmd/minishift/cmd/util/oc.go

Issue #2537 Moving message about pulling when image exists to verbose

---

cmd/minishift/cmd/config/config.go
pkg/minishift/config/validations.go
pkg/minishift/config/validations_test.go
pkg/util/proxy.go
pkg/util/proxy_test.go

Fixes #2475
Handle proxy specified without scheme

Issue #2475 Handle proxy specified without scheme

---

pkg/minishift/docker/image/oci_image_handler.go

How to test
--------------
```
$ minishift ssh
$ vi Dockerfile
FROM alpine:latest
MAINTAINER kumarpraveen.nitdgp@gmail.com
CMD pwd
$ docker build -t test:latest .
$ docker run test:latest
Edit the Dockerfile
$ vi Dockerfile
FROM alpine:latest
MAINTAINER kumarpraveen.nitdgp@gmail.com
CMD ls
$ docker build -t test:latest .
$ docker images
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
test                latest              91b283f03e13        23 minutes ago      253 MB
<none>              <none>              6e5e13dbce1f        23 minutes ago      253 MB
$ exit
Host $ minishift image export --all <= without this PR you will get the error.
```

Issue #2566 Image: Exclude <none> tag from docker image list

---

docs/source/using/run-against-an-existing-machine.adoc

This corrects some grammatical errors and applies more organization to this section of the documentation.
@praveenkumar This is an area that I'm not particularly familiar with, so please do check my wording to ensure that the information in this documentation is correct.
Thank you!

Issue #2579 Fix Run Against an Existing Machine docs

---

docs/source/using/run-against-an-existing-machine.adoc

Issue #2602 amend explicit IP address reference

---

test/integration/features/generic-driver.feature

Fix https://github.com/minishift/minishift/issues/2457

Issue #2457 Add integration test for generic driver

---

test/integration/testsuite/minishift.go
test/integration/util/util.go

Issue #2617 Some integration step definition does not report ssh failure

---

test/integration/features/cmd-config.feature
test/integration/testsuite/minishift.go
test/integration/testsuite/testsuite.go
test/integration/util/util.go

Issue #1722 implement step definition of cpu and disk size check

---

cmd/minishift/cmd/config/config.go
pkg/minishift/config/validations.go
pkg/minishift/config/validations_test.go
pkg/util/proxy.go
pkg/util/proxy_test.go

Issue #2594 Correct defaultScheme for proxy validation check

---

Makefile

This reverts commit cf7e5ac95a6e406d821a37a2728024cba93e5c11.

Issue #2582 Enabling the addon-xpaas  integration tests

---

docs/source/contributing/developing.adoc
test/integration/testsuite/testsuite.go

Issue #2053 Document available Gherkin step definitions

---

test/integration/features/addon-xpaas.feature

Fix of issue(s) : #2644
NOTE : Using Make file changes for my testing propose, later will revert back the changes before merge. 
How to test :
1. make integration GODOG_OPTS=“-tags addon-xpaas”
2.

Issue #2644 create different namespace for each template of xpaas

---

addons/htpasswd-identity-provider/README.adoc
addons/htpasswd-identity-provider/htpasswd-identity-provider.addon
addons/htpasswd-identity-provider/htpasswd-identity-provider.addon.remove
cmd/minishift/cmd/util/util.go
docs/source/using/addons.adoc
pkg/minishift/addon/manager/addon_manager_test.go
test/integration/features/basic.feature
test/integration/features/cmd-addons.feature

Fixes #2647 
Moving the add-on from https://github.com/minishift/minishift-addons/tree/master/add-ons/htpasswd-identity-provider

Issue #2647 Adding htpasswd-identity-provider add-on

---

.github/PULL_REQUEST_TEMPLATE.md

Issue #2674 add pr template for minishift

---

cmd/minishift/cmd/util/oc.go

Fixes #2679
`./minishift start && ./minishift stop && ./minishift start`

Issue #2679 Fix oc context for profile in case of restart

---

Makefile
pkg/minikube/constants/constants.go
test/integration/features/basic.feature
test/integration/features/cmd-openshift.feature
test/integration/features/experimental-flags.feature
test/integration/features/generic-driver.feature
test/integration/features/provision-various-versions.feature

Issue #2658 Making the default OpenShift version as  3.10.0

---

docs/source/using/basic-usage.adoc
pkg/util/proxy.go

Issue #2615 Disable special Char parsing for proxy for Env variable

---

docs/source/contributing/ci.adoc

Issue #2749 Removing the b2d and minikube ci job links

---

test/integration/features/basic.feature

Issue #2718 Add sleep time in millisecond instead seconds

---

Makefile
centos_ci.sh
docs/source/using/host-folders.adoc
pkg/minikube/cluster/credentials.go
pkg/minishift/addon/command/interpolation_context.go
pkg/testing/tee.go

Issue #2761 Remove duplicate words

---

cmd/minishift/cmd/openshift/set.go
cmd/minishift/cmd/openshift/view.go
docs/source/openshift/openshift-client-binary.adoc
pkg/minishift/constants/constants.go
pkg/minishift/docker/docker.go
pkg/minishift/openshift/openshift.go

Fixes #2677 
This PR is should be tested with https://github.com/knative/docs/blob/master/install/Knative-with-OpenShift.md#creating-a-new-openshift-cluster instructions.

Issue #2677 Add kube as target for openshift config command

---

Makefile

Fixes #2769 
1. make integration_all
2. 
3. 
4.

Issue #2769 Integration test timeout need to be revised for nightly

---

addons/admin-user/admin-user.addon
pkg/minishift/addon/manager/addon_manager.go

Fixes #2778 
1. $ minishift start
2. $ minishift apply che

Issue #2778 Fix openshift version metadata info for addon

---

addons/xpaas/xpaas.addon
test/integration/features/addons/addon-xpaas.feature

Issue #2782 Fix xpaas addon echo command for integration test

---

docs/source/getting-started/quickstart.adoc
test/integration/features/basic.feature
test/integration/features/cmd-openshift.feature
test/integration/features/proxy.feature

Update example repos that were moved to sclorg

---

centos_ci.sh

Fix #2791 
The release job is already running similar test as PR job
See 
https://github.com/minishift/minishift/blob/8c751ba04c027d8efe1a8a2a5324c9d64a9e3b00/centos_ci.sh#L309-L315

Issue #2791 Run similar tests for master build as that of PR build

---

pkg/minishift/registration/redhat.go

Fixes #2813 
1. MINISHIFT_ENABLE_EXPERIMENTAL=y  ./minishift start --iso-url <RHEL_iso> --no-provision
2. ./minishift ssh
3. ./docker pull registry.redhat.io/openshift3/ose-control-plane:latest => this should now able to pull the images.

Issue #2813 login to registry.redhat.io container registry

---

centos_ci.sh
test/integration/features/cmd-hostfolder.feature
test/integration/testsuite/minishift.go
test/integration/testsuite/testsuite.go
test/integration/util/util.go

Issue #2126 Adding tests for sshfs hostfolder

---

docs/source/using/run-against-an-existing-machine.adoc

Issue #2775 Add document for htpasswd-identity-provider addon

---

test/integration/features/addons/addon-htpasswd-identity-provider.feature

Fixes #2743
1. make integration GODOG_OPTS="-tags addon-htpasswd-identity-provider"
2. 
3. 
4.

Issue #2743 Test coverage for addon htpasswd-identity-provider

---

test/integration/features/stories/coolstore.feature
test/integration/templates/coolstore.yaml

Fixes #1327 
1. make integration GODOG_OPTS=-tags=coolstore

Issue #1327 Coolstore integration test failed with timeout issue

---

docs/source/using/basic-usage.adoc

as explained in the next paragraph

[Doc] Now the default image is centos

---

test/integration/features/cmd-docker-env.feature

Fixes #2838
1. make integration GODOG_OPTS="-tags cmd-docker-env"
2. 
3. 
4.

Issue #2838 Update cmd-docker-env.feature file

---

test/integration/features/cmd-openshift.feature

Fixes #2862 
1. make integration GODOG_OPTS="-tags cmd-openshift"
2. 
3. 
4.

Issue #2862 Test coverage for minishift openshift component command

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/start.go
cmd/minishift/cmd/start_preflight.go
pkg/minishift/constants/constants.go
pkg/minishift/network/settings_windows.go
pkg/minishift/network/utils.go

Fixes #2454 #2885 
One way to test if this is working properly.. start minishift in windows using the `Default Switch` and provide an IP address for it, `minishift` will try to guess the netmask, and if this works as expected the netmask should be `225.255.255.240`

Issue #2454 Fix check for Default Switch

---

pkg/minishift/docker/image/oci_image_handler.go

Fixes #2474
Make sure you also test this with an old image cache and this shouldn't break any backward compatibility of our `image cache` feature.
```
Terminal 1 $ ./minishift image export fedora
Terminal 2 $ ./minishift image export busybox => do it alomst same time.
Let's wait till both the export complete.
$ ./minishift image list  => This should now show both the images
fedora:latest
busybox:latest
```

Issue #2474 Image Cache: Add append feature for index file

---

cmd/minishift/cmd/timezone.go
pkg/minishift/timezone/timezone.go

Issue #2897 Code refactor in timezone

---

cmd/minishift/cmd/config/set_test.go
cmd/minishift/cmd/profile/profile_delete.go
cmd/minishift/cmd/root.go
cmd/minishift/cmd/util/oc.go
cmd/minishift/cmd/util/util.go
cmd/minishift/state/instance_dirs.go
cmd/testing/cli/harness.go
pkg/minishift/profile/profile.go

Issue #1402 Code refactoring around UpdateProfileConstants

---

pkg/minikube/kubeconfig/config.go
pkg/minishift/oc/oc.go
pkg/minishift/oc/oc_test.go

Fixes #2870
cc @hferentschik 
```
$ export KUBECONFIG=/tmp/foo/config
$ minishift start
$ cat /tmp/foo/config
$ oc whoami <= on the same terminal where you have exported the KUBECONFIG file.
```

Issue #2870 Honour KUBECONFIG env if set

---

test/integration/features/stories/coolstore.feature

Fixes #2927
1. make integration GODOG_OPTS="-tags coolstore"
2. 
3. 
4.

Issue #2927 Cool store test is failing in nightly

---

test/integration/features/stories/restart.feature
test/integration/testsuite/testsuite.go

Fixes  #2708
Steps to test the pull request:
1. make integration GODOG_OPTS=-tags=restart

Issue #2708 Integration test for start->stop->start scenario test

---

test/integration/features/stories/restart.feature

Fixes #2940
1. make integration GODOG_OPTS="-tags restart"
2. 
3. 
4.

Issue #2940 Update correct status of minishift

---

test/integration/features/addons/addon-registry-route.feature

Fixes #2572
1. make integration GODOG_OPTS="-tags addon-registry-route"
2. 
3. 
4.

Issue #2572 Cover more scenario in registry-route feature file

---

docs/source/getting-started/setting-up-virtualization-environment.adoc

 Issue #2866 Updated docs for virtualization env setup 

---

centos_ci.sh
docs/source/getting-started/setting-up-virtualization-environment.adoc

Issue #2924 Update docker-machine-kvm driver from 0.7.0 to 0.10.0

---

Gopkg.lock
Gopkg.toml
vendor/github.com/docker/machine/drivers/hyperv/hyperv.go
vendor/github.com/docker/machine/libmachine/libmachine.go
vendor/github.com/docker/machine/libmachine/provision/boot2docker.go
vendor/github.com/docker/machine/libmachine/provision/debian.go
vendor/github.com/docker/machine/libmachine/provision/redhat.go
vendor/github.com/docker/machine/libmachine/provision/ubuntu_systemd.go
vendor/github.com/docker/machine/libmachine/provision/ubuntu_upstart.go
vendor/github.com/docker/machine/libmachine/provision/utils.go
vendor/github.com/docker/machine/libmachine/ssh/client.go

Issue #2945 update vendor docker-machine/machine

---

pkg/minishift/config/validations.go
test/integration/features/cmd-config.feature

Issue #2926 return error when iso file does not exist

---

test/integration/features/stories/coolstore.feature

Fixes #2979 
1. make integration_all
2. 
3. 
4.

Issue #2979 Disable coolstore.feature in nightly run

---

ROADMAP.adoc

Issue #2985: Fix typo in roadmap

---

pkg/minishift/systemtray/systemtray.go

Issue #2848 use minishift command to get status for systemtray

---

docs/source/using/run-against-an-existing-machine.adoc

Issue #2991: Remove extra {}

---

ROADMAP.adoc
docs/source/openshift/openshift-client-binary.adoc
docs/source/using/experimental-features.adoc

Issue #3012 Fixing the broken links for "oc cluster up" documentation

---

docs/source/using/experimental-features.adoc

Issue #2961 Removing OKD 3.9.0 references from documentation

---

docs/source/using/basic-usage.adoc
docs/source/using/host-folders.adoc

Issue #3025 Remove minikube iso references in documentation

---

.circleci/config.yml
.travis.yml
appveyor.yml
cmd/minishift/cmd/config/config_test.go
cmd/minishift/cmd/config/view_test.go
pkg/minishift/docker/image/oci_image_handler.go
pkg/util/crypto.go
pkg/util/os/atexit/atexit.go

Issue #3059 Update go version to 1.11.2

---

docs/source/getting-started/setting-up-virtualization-environment.adoc

This makes it easier to copy/paste the command

Issue #3056 replace <username> with $(whoami)

---

.travis.yml
docs/source/contributing/ci.adoc

Issue #3024 Add worthless GH token to coverage step on Travis

---

docs/source/troubleshooting/troubleshooting-driver-plugins.adoc

Fixes #2180.
Please double-check my wording and the workaround -- unfortunately, I do not have access to a macOS environment to verify this with.

Issue #2180 Document "Error detecting VBox version" error

---

addons/redhat-registry-login/redhat-registry-login.addon
addons/redhat-registry-login/redhat-registry-login.addon.remove
cmd/minishift/cmd/util/util.go
docs/source/using/addons.adoc
pkg/minishift/addon/manager/addon_manager_test.go
test/integration/features/addons/cmd-addons.feature
test/integration/features/basic.feature

Fixes #3050 
1. `minishift addons apply xpaas-imagestreamsecret -a DOCKER_USERNAME= -a DOCKER_PASSWORD= -a DOCKER_EMAIL= `
2. Fil in the blanks :D

Issue #3050 Image stream secret for registry.redhat.io

---

centos_ci.sh

Issue #3082 Using a working GPG key for RVM

---

test/integration/features/addons/addon-registry-route.feature
test/integration/features/addons/addon-xpaas.feature
test/integration/features/basic.feature
test/integration/features/cmd-openshift.feature
test/integration/features/proxy.feature
test/integration/features/stories/coolstore.feature
test/integration/features/stories/restart.feature

Issue #2984 Make testing of app deployments more robust

---

centos_ci.sh

Issue #3102 Fix upload of artefacts in ci.centos.org

---

centos_ci.sh

Issue #3111 Fix rvm installation on centos ci

---

centos_ci.sh

Issue #3115 Re-enable docs link check in centos ci script

---

Makefile

Issue #3121 Update CentOS iso version from 1.13.0 to 1.14.0

---

Gopkg.lock
Gopkg.toml
cmd/minishift/cmd/root.go
pkg/minikube/constants/constants.go
pkg/minishift/profile/profile.go
pkg/minishift/systemtray/systemtray.go

Fixes #3003 
1. Download artifacts for [darwin](https://5814-62728051-gh.circle-artifacts.com/0/ms/darwin-amd64/systemtray/minishift) or [windows](https://5814-62728051-gh.circle-artifacts.com/0/ms/windows-amd64/systemtray/minishift.exe)
2. `minishift start`
3. `minishift profile set test` # The new profile should be shown in tray instantly
4. `minishift profile delete test` # test profile should disappear from tray instantly

Issue #3003 Use filesystem notification to update systray menu

---

.circleci/config.yml

Issue #3131 circle ci failure fix

---

.circleci/config.yml
.travis.yml
appveyor.yml

Issue #3146 update go version to 1.11.4

---

docs/source/getting-started/setting-up-virtualization-environment.adoc

Issue #3106 Adding installation steps for hyperkit binary

---

docs/source/getting-started/setting-up-virtualization-environment.adoc

Issue #3106 Fixing the typo s/If/if/

---

cmd/minishift/cmd/profile/profile_copy.go
cmd/minishift/cmd/root.go
cmd/minishift/cmd/util/util.go
pkg/minikube/constants/constants.go
pkg/minishift/constants/constants.go
test/integration/features/cmd-profile.feature

Fixes #1649 
1. minishift profile copy SRC_PROFILE_NAME NEW_PROFILE_NAME

Issue #1649 Create new profile similar to an existing profile

---

pkg/minishift/systemtray/systemtray.go

Fixes #3055 
2.  Click on the _OpenShift Web Console_ menu item.

Issue #3055 Option to open OpenShift web console from tray

---

pkg/minishift/systemtray/systemtray.go

Issue #3173 Use helper function to get status instead of running `minishift status` command

---

docs/source/using/basic-usage.adoc

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>
Fixes #3175

Issue #3175 - Remove obsolete text in Basic usage guide

---

docs/source/using/basic-usage.adoc

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>
Fixes #3178

Issue #3178 - Update Basic Usage guide

---

addons/che/templates/che-server-template.yaml
test/integration/che/cheAPI.go
test/integration/features/addons/addon-che-with-anyuid.feature
test/integration/features/addons/addon-che.feature
test/integration/features/addons/cmd-addons.feature
test/integration/testsuite/testsuite.go

Issue #2973 Che workspace like Python, PHP ... deployment fails

---

Makefile

Issue #3181 Update CentOS ISO to version v1.15.0

---

test/integration/features/addons/addon-che-with-anyuid.feature
test/integration/features/addons/addon-che.feature

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>
Fixes #3189

Issue #3189 - Remove PHP examples from integration tests

---

docs/source/troubleshooting/troubleshooting-driver-plugins.adoc

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>
Fixes #3220

Issue #3220 - remove obsolete blog post

---

.github/ISSUE_TEMPLATE.md

Support was documented in #3106 but the issue template wasn't updated

Add hyperkit to list of hypervisors in the issue template

---

docs/source/contributing/developing.adoc

changed a typo in the docs

---

pkg/minishift/registration/redhat.go

Issue #3234 correct spelling mistake retriving=>retrieving

---

addons/che/templates/che-server-template.yaml
addons/che/templates/che-workspace-service-account.yaml

Updated che template with latest upstream one
Fixes #3216

Issue #3216 update che templates

---

addons/xpaas/v3.10/xpaas-templates/fuse-apicurito.yml
addons/xpaas/v3.11/xpaas-templates/fuse-apicurito.yml

Signed-off-by: Aurélien Pupier <apupier@redhat.com>
Fixes #3198 
1. 
2. 
3. 
4.

Issue 3198 - Remove out of sync version for Apicurito Fuse builder

---

cmd/minishift/cmd/config/config.go
cmd/minishift/cmd/start_preflight.go

Issue #3170 Add preflight check for powershell and fix vmms check

---

Makefile
docs/source/contributing/developing.adoc

Now it will accept any character after the issue #<issue_number>\<space\>
Fixes #3227

Issue #3227 Fixing the validate commits to be more flexible

---

addons/che/che.addon
addons/che/templates/che-server-template.yaml
addons/che/templates/che-workspace-service-account.yaml

Fixes #3259
1. Install Che addon.
2. Create and start a workspace and then try to use terminal there. It should work fine.
3. Rollout Che deployment with a started workspace. The workspace should exist and be running after rollout finished.

Update Eclipse Che addon

---

addons/che/che.addon

Fixes https://github.com/eclipse/che/issues/13439
See referenced issue

Change plugin registry to v3

---

docs/source/contributing/ci.adoc

Issue #3283 Add new link for the master docs artifact

---

README.adoc

Issue #3285 Update README with CRC recommendation for OpenShift 4.x

---

centos_ci.sh

Issue #3298 Temporarily disable link checking for docs

---

centos_ci.sh

Issue #3336 Temporarily disable link checking for master/pr job

---

centos_ci.sh

Reverts minishift/minishift#3337

Revert "Issue #3336 Temporarily disable link checking for master/pr job"

---

test/integration/features/cmd-openshift.feature

Issue #3344 Replace node-js app used in tests with django app

---

.circleci/config.yml
.travis.yml
appveyor.yml
pkg/minikube/cluster/cluster.go
pkg/util/proxy.go
pkg/util/proxy_test.go

Issue #3375 Add deprecation message for xhyve driver

---

centos_ci.sh

Issue #3386 Temporarily disable link checking for master branch

---

centos_ci.sh

Issue #3398 Disable docs link checking for PR job too

---

centos_ci.sh

Issue #3390 Disable docs building as part of the release job

---

Makefile

Issue #3393 Bump centos iso version to 1.16.0

---

addons/xpaas/v3.11/xpaas-streams/rhdm76-image-streams.yaml
addons/xpaas/v3.11/xpaas-streams/rhpam76-image-streams.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm76-authoring-ha.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm76-authoring.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm76-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm76-prod-immutable-kieserver-amq.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm76-prod-immutable-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm76-trial-ephemeral.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-authoring-ha.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-authoring.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-kieserver-externaldb.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-kieserver-mysql.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-kieserver-postgresql.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-managed.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-prod-immutable-kieserver-amq.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-prod-immutable-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-prod-immutable-monitor.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-prod.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam76-trial-ephemeral.yaml

Issue #3425 Update xpaas image streams and templates

---

.circleci/config.yml
addons/xpaas/v3.11/xpaas-streams/rhdm77-image-streams.yaml
addons/xpaas/v3.11/xpaas-streams/rhpam77-image-streams.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm77-authoring-ha.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm77-authoring.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm77-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm77-prod-immutable-kieserver-amq.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm77-prod-immutable-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm77-trial-ephemeral.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-authoring-ha.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-authoring.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-kieserver-externaldb.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-kieserver-mysql.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-kieserver-postgresql.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-managed.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-prod-immutable-kieserver-amq.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-prod-immutable-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-prod-immutable-monitor.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-prod.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam77-trial-ephemeral.yaml
centos_ci.sh

Added rhpam77 and rhdm77 images streams and templates
Fixes #3456 
2. `minishift addons apply redhat-registry-login -a REGISTRY_USERNAME=<username> -a REGISTRY_PASSWORD=<password>`
3. `minishift addons apply xpaas`
4.  Open the webconsole using `minishift console` and try to deploy an app from xpaas templates, e.g red hat process automation`

Issue #3456 Update xpaas addons

---

docs/source/using/profiles.adoc

Issue #3466 Fix typo in profiles documentation

---

addons/xpaas/v3.11/xpaas-streams/rhdm78-image-streams.yaml
addons/xpaas/v3.11/xpaas-streams/rhpam78-image-streams.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm78-authoring-ha.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm78-authoring.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm78-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm78-prod-immutable-kieserver-amq.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm78-prod-immutable-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhdm78-trial-ephemeral.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-authoring-ha.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-authoring.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-kieserver-externaldb.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-kieserver-mysql.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-kieserver-postgresql.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-managed.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-prod-immutable-kieserver-amq.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-prod-immutable-kieserver.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-prod-immutable-monitor.yaml
addons/xpaas/v3.11/xpaas-templates/rhpam78-prod.yaml

Fixes #3480 
Added rhpam78 and rhdm78 images streams and templates
2. `minishift addons apply redhat-registry-login -a REGISTRY_USERNAME=<username> -a REGISTRY_PASSWORD=<password>`
3. `minishift addons apply xpaas`
4.  Open the webconsole using `minishift console` and try to deploy an app from xpaas templates, e.g red hat process automation`

Issue #3480 update xpaas add-ons

---

Makefile

Issue #3482 bump centos iso to v1.17.0

---

Makefile

This reverts commit 34a59297da71293f5dad5b9ffd865976c2943a46.
1. 
2. 
3. 
4.

Revert "[test] Only run xpaas feature in integration test"

---

.travis.yml

- https://about.codecov.io/security-update/

Remove codecov bash script
