- Makefile
- docs/minishift_start.md
- pkg/minikube/constants/constants.go
- pkg/minikube/constants/constants_darwin.go
- pkg/minikube/constants/constants_gendocs.go
- pkg/minikube/constants/constants_windows.go
[README](https://github.com/jimmidyson/minishift#quickstart) mentioned four vm driver options. Hence updated in the minishift start doc.
> Updated options for --vm-driver option in minishift start doc

- pkg/minikube/constants/constants.go
> Fix #174 boot2docker iso download url is broken

- deploy/iso/Dockerfile
This patch will fix b2d iso creation. https://github.com/boot2docker/boot2docker/commit/2d5e77def87a9b9daa156c44bc17d8af183a4744 what caused this issue.
> Fix #186 Building the default b2d ISO fails

- Makefile
- README.md
- docs/developing.md
A low hanging fruit in preparation for the upcoming release. What exactly should be put into the bundle? Right now I add LICENSE, README.md and the actual binary (similar to what OpenShift does with _oc_). Should it be just the binary? Thoughts? 
P.S. Ignore the first two commits, since this pull request is based on the unmerged doc changes.
> Issue #171 Making release artifacts archive bundles

- glide.lock
This also relates to CDK-46 where I am going to add go-bindata as dependency and I want to make sure that whatever gets added is based on go-bindata.
> Issue #283 Re-generating glide.lock to make sure deps are up to date

- pkg/minikube/cluster/cluster.go
I didn't edited https://github.com/minishift/minishift/blob/master/pkg/minikube/cluster/commands.go#L49 because eventually we can get rid of this file completely.
> Fix #302 minishift logs doesn't work

- cmd/minikube/cmd/ssh.go
- docs/minishift_ssh.md
Fix #339 
Now, we can run `minishift ssh 'COMMAND'` or `minishift ssh -- COMMAND`:
```
minishift ssh 'df -h'
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G    196.6M      1.6G  11% /
tmpfs                  1001.0M    172.0K   1000.9M   0% /dev/shm
/dev/sda1                17.9G    785.1M     16.2G   5% /mnt/sda1
cgroup                 1001.0M         0   1001.0M   0% /sys/fs/cgroup
/dev/sda1                17.9G    785.1M     16.2G   5% /mnt/sda1/var/lib/docker/aufs
tmpfs                     1.8G    196.6M      1.6G  11% /var/lib/origin/openshift.local.volumes
.....
```
```
minishift ssh -- df -h                             
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G    196.6M …
```
> Issue #339 Fix 'minishift ssh' help message

- cmd/minikube/cmd/root.go
This will fix the issue for unwanted error message if user try a missing command.
```
06:15 $ ./minishift adfja
Error: unknown command "adfja" for "minishift"
Run 'minishift --help' for usage.
06:15 $ ./minishift ssp
Error: unknown command "ssp" for "minishift"
Did you mean this?
ip
ssh
stop
Run 'minishift --help' for usage.
```
> Issue #370 Showing internal errors on missing commands

- centos_ci.sh
Fix #435 . 
Previously not using github jenkins plugin. Enabled with this PR https://github.com/minishift/minishift-ci-jobs/pull/17
> Issue #435 Enable CI when a push to master occurs

- cmd/minishift/main.go
Fix for issue #434. 
This should make the driver selection work again.
> Issue #434 Resurrecting call to machine.StartDriver()

- centos_ci.sh
Fix #474 
Previous approach of rsync with `--rsync-path` was not working as expected. Now using `--relative` option which seems to be working. Like here https://ci.centos.org/job/minishift-b2d-iso-pr/36.
> Issue #474 Enable CI to upload master branch artifacts

- cmd/minishift/cmd/delete.go
- cmd/minishift/cmd/root.go
- cmd/minishift/cmd/root_test.go
- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_test.go
- pkg/minikube/cluster/cluster.go
- pkg/minishift/config/config.go
- pkg/minishift/config/config_test.go
Adding *WIP* as tests are remaininig.
Others things looks fine as per my opinion except the naming part (which I always find hard :smile: ). Suggestions are welcome.
```
$ cat ~/.minishift/machines/minishift/instance-data.json
{
"OcPath": "/home/budhram/.minishift/cache/oc/v1.4.1/oc"
}%
```
```
$ minishift delete   
ocPath in delete  /home/budhram/.minishift/cache/oc/v1.4.1/oc
Deleting the Minishift VM...
Minishift VM deleted.
```
> Issue #487 Introduce minishift-data.json to store oc path

- docs/source/getting-started/docker-machine-drivers.adoc
Added manual install steps for xhyve, similar to the KVM steps. Pushed the existing steps for compiling Xhyve as a note to be used only if the binary fails to work.
> Issue #466 Improved manual install steps for xhyve driver.

- docs/source/using/managing-minishift.adoc
Fix [#614](https://github.com/minishift/minishift/issues/614) 
The command info finally link this page: [minishift_openshift_list-versions](https://minishift.io/docs/minishift_openshift_list-versions.html)
> Issue #614 Use the new command to list the OpenShift versions.

- cmd/minishift/cmd/hostfolder/add.go
- cmd/minishift/cmd/hostfolder/hostfolder.go
- cmd/minishift/cmd/hostfolder/list.go
- cmd/minishift/cmd/hostfolder/mount.go
- cmd/minishift/cmd/hostfolder/remove.go
- cmd/minishift/cmd/hostfolder/umount.go
Fixes #693 
This PR provides proofreading of the doc strings for the hostfolder command and sub-commands.
NOTE: Unlike other commands (i.e. addon, config), the actual file names for the sub-commands don't include the parent command in the file name (i.e. "hostfolder_add.go" vs. "add.go"). Not sure if this is a problem but it isn't consistent.
cc @gbraad @hferentschik  @LalatenduMohanty
> Issue #693 edited doc strings for hostfolder command

- pkg/minishift/oc/oc.go
- pkg/minishift/oc/oc_test.go
- pkg/util/cmd/split_args.go
- pkg/util/cmd/split_args_test.go
Addresses issue #729 
Pretty much as suggested in issue. Added some more comments and additional unit test.
> Issue #729 Adding a helper function to split command string

- addons/anyuid/anyuid.addon
- cmd/minishift/cmd/start.go
- pkg/minishift/addon/command/oc_command.go
- pkg/minishift/addon/manager/addon_manager.go
- pkg/minishift/addon/parser/addon_parser_test.go
Addresses issue #856
- Once persistent volumes are created global permissions will be set to allow pods to write to persistent volume
- Silenced oc stdout for more consistent output diring bootstrap
- Adding echo statements to anyuid add-on to make it more explicit what the add-on does
> Issue 856 Introduce method to port configure persistent volumes

- cmd/minishift/cmd/start.go
This is very trivial since `--forward-port` is only applicable for OSx from `oc cluster up` prospective and since as part of minishift we always run it in a Linux VM.
> Issue #512 Disable forward-port flag from minishift start

- cmd/minishift/cmd/start.go
- docs/source/using/troubleshooting.adoc
- pkg/minishift/registration/redhat.go
- pkg/minishift/registration/redhat_test.go
- pkg/util/utils.go
- pkg/util/utils_test.go
Basically the way sshCommander works is it will take the string as it is and then start ssh session. when it start session it is always be a new shell so if we want to escape special characters then we need to make sure string we we are passing should have `'<Password>'`.
> Issue #878 Fail to escape password with special charachers

- test/integration/features/basic.feature
- test/integration/integration_test.go
- test/integration/util/util.go
I did test and it works as expected but user should have RHN username/password as environment variable. 
One test scenario fail because it's specific to b2d image.
```cucumber
Scenario: User is able to set custom Docker specific environment variables
Given Minishift has state "Running"
When executing "minishift ssh cat /var/lib/boot2docker/profile" succeeds
Then stdout should contain
"""
export "FOO=BAR"
export "BAZ=BAT"
"""
--- Failed steps:
Then  stdout should contain # features/basic.feature:62
Error: Output did not match. Expected: export "FOO=BAR"
export "BAZ=BAT", Actual: 
```
> Issue #874 Implementation to run integration test for downstream bits

- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_test.go
- pkg/minikube/cluster/cluster.go
- pkg/minishift/cache/oc_caching.go
- pkg/minishift/cache/oc_caching_test.go
- pkg/minishift/cache/openshift_caching.go
- pkg/util/github/github.go
- pkg/util/github/github_test.go
- pkg/util/utils.go
This patch will modify `http` client in case of proxy and use it to download iso and oc binary. Please test it, for me working as expected I can see traffic is going from proxy server.
> Issue #718 Downloading initial ISO and oc binary should support HTTP proxy

- test/integration/integration_test.go
- test/integration/minishift.go
Addresses issue #922
Fixing logical mistake in executingMinishiftCommandSucceedsOrFails() and renaming `success` variable to `failure` which better suits the result of `lastCommandOutput.ExitCode != 0 || len(lastCommandOutput.StdErr`.
Moved `s.Step(`executing "minishift ([^"]*)" (.*)$`, executingMinishiftCommandSucceedsOrFails)` before step for executingMinishiftCommand as this was matching first and due to this fact executingMinishiftCommandSucceedsOrFails() has never been actually used.
> Issue #922 Step '"minishift start" succeeds' does not fail when oc download fails

- cmd/minishift/cmd/console.go
- test/integration/features/basic.feature
> Issue #929 Alias 'minishift dashboard' to 'minishift console'

- .travis.yml
@praveenkumar @LalatenduMohanty 
The new Trusty image on Travis CI failed due to #1172
> Issue #1172 Fix Travis CI for Trusty

- docs/source/using/troubleshooting.adoc
Fixes issue #1152 
This PR covers a troubleshooting entry where we warn users not to install packages or store large files in the Minishift VM root filesystems, and suggest workarounds.
Approved by @gbraad before submitting.
> Issue #1152 troubleshooting entry about exceeding root filesystem overlay size

- Makefile
- centos_ci.sh
- docs/source/contributing/ci.adoc
- docs/source/contributing/releasing.adoc
Fix #786 
Last successful automated job was https://ci.centos.org/job/minishift-release/41/ which released https://github.com/minishift-bot/minishift/releases/tag/v1.2.13.
Apart from `TODO` comments code is ready for release job.
Will update the TODO part after final comment. 
You can try running the build using the instruction given in `contributing/release > Automated Release` section.
Use `RELEASE_VERSION` apart from version listed [here](https://github.com/minishift-bot/minishift/tags) and `MILESTONE_ID` from [closed milestones](https://github.com/minishift/minishift/milestones?state=closed). I used 15 and 17.
> Issue #786 Automated release job via CentOS CI

- .gitlab-ci.yml
- cmd/minishift/cmd/oc_env_test.go
Added GitLab CI runner definition to build on a GitLab instance. Example:
* https://gitlab.com/gbraad/minishift/-/jobs/28627751
* https://gitlab.com/minishift/minishift/-/jobs/28634280
`oc_env_test.go` needed to be given a forced shell, else the test fails with:
```
=== RUN   Test_unix_oc_path
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
--- FAIL: Test_unix_oc_path (0.00s)
oc_env_test.go:28: Unexepcted error: Error: Unknown shell
```
Note: running with `bash -c "make test"` did not make a difference
> Issue #460 Add GitLab CI runner

- scripts/release/issue-list.sh
Fix #1237 
```
$ ./scripts/release/issue-list.sh -r minishift -m 23
- Issue [#1235](https://github.com/minishift/minishift/issues/1235) (bug) - Wrong version info in v1.4.0 binaries
$ ./scripts/release/issue-list.sh -r minishift -m 22
- Issue [#1133](https://github.com/minishift/minishift/issues/1133) (feature) - Function configContains in integration_test.go does not work properly
- Issue [#1121](https://github.com/minishift/minishift/issues/1121) (bug) - Possible error in delete/registration code
- Issue [#1123](https://github.com/minishift/minishift/issues/1123) (bug) - Instructions for manual installation of xhyve driver do not work on Sierra
- Issue [#1153](https://github.com/minishift/minishift/issues/1153) (bug) - Proxy not set for Docker engine
- Issue …
```
> Issue #1237 Don't show empty headers in release notes

- docs/source/getting-started/installing.adoc
- docs/source/using/host-folders.adoc
Fix #1281 
I have searched through all documentation. Could only found these many occurances.
> Issue #1281 Update word 'Mac' with 'macOS'

- test/integration/integration_test.go
This PR on several places changes matching groups from `([^"]*)"` to `(.*)"` as there is potential need to be able to match inputs which contain quotes.
> Issue #1289 Update regex matching in test suite

- cmd/minishift/cmd/openshift/service.go
> Issue #928 Add a '-u' short alternative to `--url` for 'minishift openshift service' command

- centos_ci.sh
- test/integration/features/cmd-config.feature
- test/integration/features/cmd-openshift.feature
- test/integration/features/cmd-version.feature
- test/integration/features/provision_earlier_version.feature
- test/integration/features/proxy.feature
Some functionality of `minishift config` and its subcommands is already tested in basic.feature, but this test tries to go a bit further:
- tests should-fail cases for config set - wrong values, formats, types etc,
- tests should-pass cases for config set,
- checks if values like memory, cpus, disk-size and some others are actually applied on startup,
- do few other checks for unset and view sub-commands.
> Issue #1319 - Add integration test for config cmd

- Makefile
- docs/source/contributing/developing.adoc
This pr comprises two make test functionality make integration_smoke and make integration_all. 
i have executed this functionality both with upstream and downstream. Coolsrore is not added to the integration_all as there is a ongoing issue #1327 and proxy feature has some problem i.e. it hangs in step ```oc rollout status deploymentconfig ruby-ex``` while run along with rest of the features sequentially  ```-tags basic,cmd-openshift,command,flags,openshift-version,proxy -format pretty```, however standalone proxy feature ```make integration GODOG_OPTS="-tags basic -format pretty"```runs successfully without any error. 
we can take the proxy feature in a separate issue atm.
Here are the some part of logs 
On master
```
$ make integration_smoke
.
.
14 scenarios (14 passed)
52 steps (52 …
```
> Issue #1216 Improve `make integration` to be friendlier to use

- Makefile
- centos_ci.sh
- docs/source/contributing/developing.adoc
Fix #1446 
* Also updated centos_ci.sh script to use friendlier version to run
integration tests
> Issue #1446 Add way to add GODOG options for 'make integration_all'

- cmd/minishift/cmd/openshift/version.go
- cmd/minishift/cmd/start_preflight.go
- cmd/minishift/cmd/status.go
- pkg/minishift/openshift/version/openshift_versions.go
- test/integration/util/util.go
Have to include storage piece also.
Current output
```
$ ./minishift status
VM: Running
OpenShift: Running (openshift v3.6.0+c4dd4cf)
```
> Issue #1247 Extend status command to provide more details

- Makefile
- docs/source/contributing/developing.adoc
- test/integration/integration_test.go
Provides ability to pass Minishift commands to be run before each feature.
This can be used to test Minishift in non-vanilla state easily without need
of use of environmental variables.
> Issue #1436 - Add ability to manipulate config before features start

- test/integration/features/cmd-config.feature
Mini update in cmd-config.feature which now fails on Mac machines.
> Issue #1471 Make expected memory value in cmd-config.feature less strict

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/root.go
- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_preflight.go
- docs/source/using/managing-minishift.adoc
- glide.lock
- glide.yaml
- pkg/minishift/clusterup/clusterup.go
- pkg/minishift/config/featuretoggles.go
- pkg/minishift/config/validations.go
- pkg/minishift/config/validations_test.go
- pkg/minishift/network/settings.go
- pkg/minishift/network/settings_darwin.go
- pkg/minishift/network/settings_linux.go
- pkg/minishift/network/settings_test.go
- pkg/minishift/network/settings_windows.go
- pkg/util/strings/strings.go
- pkg/util/strings/strings_test.go
Fixes #1316
How to test:
* CentOS ISO needed: http://artifacts.ci.centos.org/minishift/minishift-centos-iso/pr/164/
```powershell
PS> $env:MINISHIFT_ENABLE_EXPERIMENTAL="y"
PS> $env:HYPERV_VIRTUAL_SWITCH="Wireless"
PS> minishift.exe start --network-ipaddress 10.0.21.40 --network-gateway 10.0.21.1
```
```powershell
PS> New-NetNat -Name SharedNAT -InternalIPInterfaceAddressPrefix 10.0.75.1/24
PS> $env:MINISHIFT_ENABLE_EXPERIMENTAL="y"
PS> $env:HYPERV_VIRTUAL_SWITCH="DockerNAT"
PS> minishift.exe start --network-ipaddress 10.0.75.124 --network-gateway 10.0.75.1
```
Note 1: the `New-NetNat` preparation step is necessary when using DockerNAT.
Note 2: `--network-gateway` is needed for outside communication, else SSH will fail to respond to connection requests, and downloads would never start. A …
> Issue #1316 Set IP address (Hyper-V only)

- centos_ci.sh
> Issue #1527 Fix CentOS CI script to not fail when minibot URL is not reachable

- test/integration/integration_test.go
- test/integration/proxy/proxy.go
- test/integration/util/integration_logger.go
- test/integration/util/util.go
Tests will now provide more information when an error happens, which should save some time when issues on machines happens.
One problem is, that logFile.Close() returns an error, no idea why and the error message is not really useful: `invalid argument`.
> Issue #1535 Add error checks into integration tests

- docs/source/contributing/index.adoc
Let me know if this isn't what was desired or if any changes need to take place.
Notes:
Linked as "Contribution guidelines" in order to be consistent with the header casing in **_CONTRIBUTING.adoc_**. Linked directly to the `#contributing-guidelines` anchor in order to make the guidelines immediately visible and clear when the link is visited.
> Issue #1567 Make CONTRIBUTING.adoc more discoverable

- test/integration/util/integration_logger.go
Quick fix for #1579 which causes problems on Windows machines.
> Issue #1579 Remove colons from filename of integration test log

- docs/source/_topic_map.yml
- docs/source/contributing/writing-docs.adoc
- docs/source/getting-started/quickstart.adoc
- docs/source/getting-started/setting-up-driver-plugin.adoc
- docs/source/getting-started/uninstalling.adoc
- docs/source/openshift/index.adoc
- docs/source/using/addons.adoc
- docs/source/using/basic-usage.adoc
- docs/source/using/docker-daemon.adoc
- docs/source/using/experimental-features.adoc
- docs/source/using/host-folders.adoc
- docs/source/using/image-caching.adoc
- docs/source/using/index.adoc
- docs/source/using/profiles.adoc
- Rename "Managing Minishift" to "Basic Commands". Naming is ambiguous
- Extract image caching and experimental features in their own topics
- Adjust cross-links
- Align header styles, eg headers should use present continuous
> Issue #1600 Restructuring the usage topic

- cmd/minishift/cmd/start_preflight.go
I found it'd be useful to have the right links in the error messages, making it  bit easier for the user to find that info.
Addresses issue #1636
> Issue #1636 Adding doc links to preflight checks

- docs/source/getting-started/installing.adoc
- docs/source/getting-started/setting-up-driver-plugin.adoc
- docs/source/openshift/openshift-client-binary.adoc
- docs/source/troubleshooting/troubleshooting-driver-plugins.adoc
- docs/source/troubleshooting/troubleshooting-getting-started.adoc
- docs/source/using/basic-usage.adoc
* Use `PS>` consistently for PowerShell
* Use `C:\>` consistently for Command Prompt
* Replace slashes in Windows-specific paths with backslashes
* Refer to the Minishift binary in Windows-specific contexts as `minishift.exe`
> Issue #1613 use consistent Windows drive letters and prompts

- Makefile
- centos_ci.sh
- docs/Dockerfile
- docs/docker-entrypoint.sh
- docs/source/contributing/writing-docs.adoc
- docs/source/using/profiles.adoc
- Update CentOS CI setup to not explcitly pull docs builder image
- Enable docs build on Appveyor
Addresses issue #944
> Issue #944 Docs build image which does not require UID at image build time

- docs/source/contributing/developing.adoc
- docs/source/contributing/index.adoc
- docs/source/contributing/releasing.adoc
- docs/source/contributing/writing-docs.adoc
- docs/source/getting-started/installing.adoc
- docs/source/getting-started/quickstart.adoc
- docs/source/getting-started/setting-up-driver-plugin.adoc
- docs/source/getting-started/uninstalling.adoc
- docs/source/getting-started/updating.adoc
- docs/source/openshift/exposing-services.adoc
- docs/source/openshift/openshift-client-binary.adoc
- docs/source/openshift/openshift-docker-registry.adoc
- docs/source/troubleshooting/troubleshooting-driver-plugins.adoc
- docs/source/troubleshooting/troubleshooting-getting-started.adoc
- docs/source/using/addons.adoc
- docs/source/using/basic-usage.adoc
- docs/source/using/docker-daemon.adoc
- docs/source/using/experimental-features.adoc
- docs/source/using/host-folders.adoc
- docs/source/using/image-caching.adoc
- docs/source/using/profiles.adoc
Applied:
- Title casing
- Styling of file paths, environment variables, etc.
- Block-style admonitions
- One sentence per line
- Wording consistency ("command line" versus "command-line")
- Minimal rewriting
> Issue #1604 Correct inconsistencies in documentation

- cmd/minishift/cmd/start.go
- pkg/minishift/network/settings_darwin.go
- pkg/minishift/network/settings_linux.go
- pkg/minishift/network/settings_windows.go
startHost is already reading the VM driver from the config.  We can pass this value in directly rather than reading it out of the config a second time.
> Issue #1503 Use vmdriver variable instead of reading from config

- cmd/minishift/cmd/delete.go
- cmd/minishift/cmd/profile/profile_delete.go
Fixes #1705
Added `-f` shorthand to the `delete` and `profile delete` commands.
Please let me know if I have missed any command.
> Issue #1705 Add -f to delete commands

- Makefile
- centos_ci.sh
- docs/Rakefile
Addresses #1729 
This pull request tries to dynamically deal with cleaning up generated ditaa images (without having to explicitly list them). It also makes sure that generating the tarball for openshift.org gets build from a clean source directory. 
Whether the existence of the image in the tarball is really the reason for failure we are seeing I am not sure off, but this change makes sense regardless.
> Issue #1729 Making sure generated images gets removed in clean target

- centos_ci.sh
- docs/source/contributing/ci.adoc
Fix #1570
Job is ready in CentOS CI, last successfully performed here https://ci.centos.org/job/minishift-nightly/10/console with same checks as PR build.
This PR add necessary changes for nightly build.
> Issue #1570 Nightly job integration in centos_ci.sh script

- cmd/minishift/cmd/addon/addon_install.go
- cmd/minishift/cmd/update.go
Adds `-f` shorthand to the `update` and `addon install` commands.
Fixes #1759
> Issue #1759 Add -f to other commands

- centos_ci.sh
- docs/source/contributing/ci.adoc
Fix #1761
Tested with job https://ci.centos.org/job/minishift-pr/2841/console after tweaking `centos_ci.sh` script go via `origin/master` branch condition.
> Issue #1761 Maintain a published docs against master branch

- docs/source/contributing/writing-docs.adoc
Fix #1814 
The issue with curl command in bash is that string containing variable interpolation need extra string so that it got interpolated and passed as proper string in JSON over the wire.
> Issue #1814 Fix curl command to trigger minishift-docs job

- Makefile
- docs/source/contributing/developing.adoc
- test/integration/features/cmd-docker-env.feature
- test/integration/features/cmd-oc-env.feature
- test/integration/integration_test.go
- test/integration/minishift.go
- test/integration/util/checks.go
- test/integration/util/shell.go
Changes:
- adds ability to run commands in shell instance - for now just bash
- adds feature for docker-env command
- moves some check functions to util package
TBD:
- add support for other shells (shouldn't be hard)
- add feature for oc-env command (shouldn't be hard)
I will appreciate any feedback on this PR.
> Issue #1332 Add integration tests for docker-env and oc-env

- Makefile
> Issue #1825 Increase the timeout of integration tests

- cmd/minishift/cmd/image/export.go
- cmd/minishift/cmd/image/import.go
- cmd/minishift/cmd/start.go
- pkg/minishift/docker/image/image_handler.go
- pkg/minishift/docker/image/oci_image_handler.go
- test/integration/features/cmd-image.feature
Addresses #1837
- Making sure that on empty cache the start command is not printing misleading error messages
- Changing ImageHandler.ExportImages and ImageHandlerImportImages to also returns the list of successfully imported/exported images
> Issue #1837 Making sure start command does not print misleading messages

- cmd/minishift/cmd/root.go
Default profile name 'minishift' shouldn't be part of checkForValidProfileOrExit function because this is already a valid profile name and globally true.
> Issue #1861 Ignore checkForValidProfileOrExit function for default profile

- docs/source/contributing/ci.adoc
> Issue #1868 Issue #1868 Fix 'make link_check_docs' after nightly URL update

- cmd/minishift/cmd/config/config.go
Fix #1874
```
$ minishift config | grep cache-images
```
> Issue #1874 Don't show 'cache-images' config view listed properties

- Makefile
- docs/Gemfile
- docs/Gemfile.lock
Fix #1911 
Now, not able to see those security warning in my fork
> Issue #1911 Github security warning for nokogiri version < 1.8.1

- docs/source/using/profiles.adoc
Fix #1937 
This is how it is displayed now.
> Issue #1937 Use warning sign instead of tip for clear-cache info

- cmd/minishift/cmd/root.go
- docs/source/using/image-caching.adoc
- pkg/minikube/constants/constants.go
- pkg/util/strings/strings.go
- test/integration/features/addon-xpaas.feature
- test/integration/features/basic.feature
- test/integration/features/cmd-addons.feature
- test/integration/features/cmd-config.feature
- test/integration/features/cmd-docker-env.feature
- test/integration/features/cmd-image.feature
- test/integration/features/cmd-oc-env.feature
- test/integration/features/cmd-openshift.feature
- test/integration/features/coolstore.feature
- test/integration/features/flags.feature
- test/integration/features/profile.feature
- test/integration/features/provision_earlier_version.feature
- test/integration/features/provision_various_versions.feature
- test/integration/features/proxy.feature
- test/integration/integration_test.go
- test/integration/minishift.go
Fix #1799 and #1798 
The verifying of cached images is not based on the suggestion provided by Hardy here https://github.com/minishift/minishift/issues/1799#issuecomment-349320277.
It is more based on the output of `minishift image list` suggested by @agajdosi . 
In both cases, we had to poll for something like in monitoring PID case, we have to poll for process end.
Tested following cases:
- Fresh start
- Fresh start with image-caching true
- Fresh start with image-caching false
> Issue #1799 Make image caching default and run integration tests 

- Makefile
- docs/source/contributing/developing.adoc
- scripts/boilerplate/boilerplate.py
- test/integration/integration_test.go
- test/integration/util/test-preparation.go
This PR adds `COPY_OC_FROM` parameter to the integration tests. It can be used to test the Minishift with local version of oc binary and thus can be used for testing of unreleased oc versions. The oc binary must be placed in 2 levels of directories which follows the format which Minishift uses for storing the oc binary in its home: `<version>/<platform>/oc(.exe)`. This whole structure is then copied into the `MINISHIFT_HOME/cache/oc/` before the start of the feature and thus can be used in the following tests.
For example:
- download oc version 3.7.23
- put it into ~/custom-oc/v3.7.23/linux/oc
- run `make integration COPY_OC_FROM=~/custom-oc/v3.7.23/linux/oc RUN_BEFORE_FEATURE="config set openshift-version v3.7.23"`
Was thinking about creating …
> Issue #1585 - Add option to use different oc binary in integration tests

- test/integration/features/addon-xpaas.feature
- test/integration/features/basic.feature
- test/integration/features/coolstore.feature
- test/integration/features/proxy.feature
- test/integration/integration_test.go
- test/integration/minishift.go
- test/integration/util/util.go
This PR should prevent `freeze` of integration tests on rollout step (when there are problems with rollout) so the tests will continue and not quit after one or two hours. Also it gives us more feedback on the failure which should help us debug better coolstore and other cases when rollout fails.
Changes:
- adds timeout to rollout step, it is needed parameter so it also adds 1200 seconds timeout to all features
- improves feedback from the rollout step, it now prints out stdout and stderr for all services instead of vague `not all successfully rolled out`
- all improvements in feedback also shows up in the log file
- added func runCommandWithTimeout() into `test/integration/minishift.go` 
- func runCommand() in `test/integration/minishift.go` now has default timeout of one hour
The last …
> Issue #1703 Add timeout to rollout step

- cmd/minishift/cmd/completion.go
Modified the source code from Minikube for Minishift.
```
$ minishift completion  --help
Outputs minishift shell completion for the given shell (bash or zsh)
This depends on the bash-completion binary.  Example installation instructions:
OS X:
$ brew install bash-completion
$ source $(brew --prefix)/etc/bash_completion
$ minishift completion bash > ~/.minishift-completion  # for bash users
$ minishift completion zsh > ~/.minishift-completion  # for zsh users
$ source ~/.minishift-completion
Fedora:
$ dnf install bash-completion
$ minishift completion bash > ~/.minishift-completion  # for bash users
$ source ~/.minishift-completion
Additionally, you may want to output the completion to a file and source in your .bashrc
Note for zsh users: [1] zsh completions are only supported in versions …
```
> Issue #522 Add bash completion to Minishift

- pkg/minishift/provisioner/minishift_provisioner.go
- pkg/minishift/provisioner/minishift_provisioner_test.go
This depends on https://github.com/minishift/minishift-centos-iso/pull/207. In case you want to test it out then fetch the ISO from http://artifacts.ci.centos.org/minishift/minishift-centos-iso/pr/207 and use this PR against it. After that do `minishift ssh` and execute `docker info` it should show below.
```
[...]
Server Version: 1.12.6
Storage Driver: overlay2
Backing Filesystem: xfs
Native Overlay Diff: true
Logging Driver: journald
[...]
```
> Issue #1639 Switch to overlay2 as default storage driver for docker

- test/integration/testsuite/minishift.go
Fix #1994
This will help in debugging rollout steps which is often used in application deployment which is the reason of nightly jobs failure in Minikube ISO.
> Issue #1994 Show app builds logs during integration tests on failure

- pkg/minishift/addon/manager/addon_manager_test.go
- pkg/minishift/addon/parser/addon_parser.go
- pkg/minishift/addon/parser/addon_parser_test.go
- test/testdata/testaddons/addon-dir-mismatch/addondirmismatch.addon
Fix #1672 and #2014 
Tried with following addon
```
$ mkdir demoaddon
$ cat demoaddon/demoaddon.addon
echo This is demo addon with variable FOO whose value is #{FOO}
```
```
$ minishift addon install demoaddon
Add-on installation failed with the error: Unable to parse specified addon: Add-on directory name 'demoaddon' should match to addon name 'demo-addon'
```
> Issue #1672 Show error when addon dir name is not equal to its name

- test/integration/features/cmd-profile.feature
Fix : #1889 #2039 
I added tag @minishift-tag to the feature files. Some feature files can be restructured without loosing the usecase integrity to run on both upstream and downstream use. Files like ```cmd-image, provision-earlier-version``` are only for upstream integration test as this is very difficult to restructure and keep the usecase integrity intact for both testing.
So this pr is dealing with these feature files, and as a solution to the downstream it avoid merge conflict with same downstream feature file. In the downstream repo same file should be created with name cdk-*.feature and @cdk-only tag. For example 
cdk-cmd-image.feature
```
@cmd-image @command @cdk-only
Feature: Basic image caching test
As a user I am able to import and export container images from a local OCI …
```
>  Issue #1889 #2039 Update profile test to disable image caching 

- addons/registry-route/registry-route.addon
- cmd/minishift/cmd/openshift/registry.go
- cmd/minishift/cmd/openshift/version.go
- cmd/minishift/cmd/status.go
- pkg/minishift/addon/manager/addon_manager.go
- pkg/minishift/openshift/registry.go
- pkg/minishift/openshift/version/openshift_versions.go
Openshift >= v3.7.0 we don't need to specify the port number `443` for registry route.
> Issue #1933 Allow docker push from exposed registry-route

- CONTRIBUTING.adoc
> Issue #2057 Update `CONTRIBUTING.adoc` to contain the format for Commit message

- cmd/minishift/cmd/start_preflight.go
- pkg/minikube/cluster/cluster_darwin.go
Once we enable rawdisk as true for the driver then mount drive created as `/mnt/vda1` instead `/mnt/sda1`
```
minishift config set skip-check-storage-mount true
```
> Issue #2067 Set rawdisk as default for xhyve driver

- pkg/minishift/openshift/version/openshift_versions.go
- pkg/minishift/openshift/version/openshift_versions_test.go
Fixes: #2069
```
$ minishift openshift version list
The following OpenShift versions are available: 
- v1.4.1
- v1.5.0
- v1.5.1
- v3.6.0
- v3.6.1
- v3.7.0
- v3.7.1
- v3.9.0-alpha.3
```
> Issue #2069 Print origin versions from github releases instead of dockerhub

- Gopkg.lock
- Gopkg.toml
- test/integration/features/cmd-config.feature
Also updating Godog to latest release which fixes incomplete failure report when scenario outlines are used.
> Issue #2150 Disk validation fails in cmd-config.feature on MacOS

- cmd/minishift/cmd/start_preflight.go
- pkg/minishift/network/settings.go
@gbraad Following is the error message now in case of no internet connection to host.
```
$ ./minishift start --openshift-version v3.7.1
-- Checking if requested OpenShift version 'v3.7.1' is valid ... Offline ==>  This one
-- Checking if requested OpenShift version 'v3.7.1' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... 
Driver is available at /usr/local/bin/docker-machine-driver-xhyve
Checking for setuid bit ... OK
```
> Issue #2102 Add Offine error message for pre-flight check

- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_preflight.go
- pkg/minishift/network/settings.go
`net.Dial("tcp", address)` did not use the proxy settings which led it to wrongly report a faulty Internet connection when in reality it just didn't know about the proxies.
> Issue #1628 Fix Internet connectivity check to honor proxy settings and use HTTP

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/start.go
- test/integration/features/cmd-config.feature
See https://github.com/openshift/origin/pull/19209 for more info
See #2248 for more info
/cc: @deads2k @jcantrill
> Issue #2234 remove flags for metrics, logging and service catalog

- pkg/minishift/registration/redhat.go
Fixes: #1972 
```
Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username lsdjfl --password ********
err     : exit status 70
output  : Invalid username or password. To create a login, please visit https://www.redhat.com/wapps/ugc/register.html
Registering to: subscription.rhsm.redhat.com:443/subscription
```
> Issue #1972 Redact password from ssh commander upon registration

- cmd/minishift/cmd/env.go
- cmd/minishift/cmd/oc_env.go
- cmd/minishift/cmd/oc_env_test.go
- cmd/minishift/cmd/oc_env_test_windows.go
- cmd/minishift/cmd/util/util.go
- pkg/util/shell/shell.go
- test/integration/features/cmd-oc-env.feature
The test is currently failing because I can't figure out how to get a `libmachine.API` to pass into it. Help appreciated.
> Issue #2269 Add --no-proxy flag to oc-env

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/preflight_artifacts.go
Fixes #2318 
Here is the step to test this PR:
Without this PR
```
$ minishift start --extra-clusterup-flags "--service-catalog"
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
Driver is available at /usr/local/bin/docker-machine-driver-xhyve
Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... Flag 'extra-clusterup-flags' is not supported for oc version …
```
> Issue #2318 Fix preflight check for extra-clusterup-flags

- test/integration/testsuite/minishift.go
- test/integration/testsuite/testsuite.go
Fix #2337
Require for https://issues.jboss.org/browse/CDK-271. Also, potential use case for upstream as well.
> Issue #2337 Add test step to delete the minishift home dir

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/preflight_artifacts.go
- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_preflight.go
- docs/source/troubleshooting/troubleshooting-getting-started.adoc
Fixes  issue #2267
Adds a flag --skip-startup-checks which is by default false
but when set to true it will skip the preflightchecks
> Issue #2267 adds a flag --skip-startup-checks

- cmd/minishift/cmd/start_preflight.go
The error does not look nice.. FAIL is printed after the error msg, this is to be fixed in #2327 
```
[minishift]$ minishift start
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... 
Hit github rate limit: GET https://api.github.com/repos/openshift/origin/releases/tags/v3.9.0: 403 API rate limit exceeded for 125.16.100.118. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 55m29.059306046s FAIL
```
> Issue #2307 show github api rate limit error for origin check

- Gopkg.lock
- Gopkg.toml
- cmd/minishift/cmd/hostfolder/add.go
Fiexs: #2331 
Not sure if we want to show it expanded or keep it as `~` in the o/p of command `minishift hostfolder list`
> Issue #2331 expand ~ to homedir in source path while adding sshfs hostfolder interactively

- Gopkg.lock
- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/delete.go
- cmd/minishift/cmd/start.go
- docs/source/using/experimental-features.adoc
- pkg/minikube/cluster/cluster.go
- pkg/minikube/cluster/cluster_common.go
- pkg/minikube/constants/constants_darwin.go
- pkg/minikube/constants/constants_linux.go
- pkg/minikube/constants/constants_windows.go
- pkg/minikube/machine/client.go
- pkg/minishift/clusterup/clusterup.go
- pkg/minishift/provisioner/minishift_detector.go
- pkg/minishift/provisioner/minishift_detector_test.go
- pkg/minishift/provisioner/minishift_provisioner.go
- pkg/minishift/provisioner/minishift_provisioner_test.go
- pkg/minishift/provisioner/utils.go
@LalatenduMohanty this PR is still work I just rebased it and tested against a minishift profile which I started with `--no-provision`
```
$ minishift profile set foo
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ minishift start --no-provision
$ minishift ip
192.168.64.3
$ minishift profile set minishift
$ minishift start --vm-driver generic --remote-ip-address 192.168.64.3 --remote-ssh-username docker --ssh-key-to-connect-remote ~/.minishift/profiles/foo/machines/foo/id_rsa
```
1. How to test on a remote centos/rhel/fedora box.
- Assume you have a remote host which has IP as `10.1.1.1`
```
Host$ ssh-copy-id <user>@10.1.1.1  "Make sure user have sudo access without password or use root"
Host$ ssh <user>@10.1.1.1 
Remote_VM$ yum install -y docker net-tools
Remote_VM$ systemctl start docker …
```
> Issue #392 Implement ability to run minishift against an existing VM

- cmd/minishift/cmd/start_preflight.go
- cmd/minishift/cmd/status.go
Below is what you get now.
```
$ ./minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  17% of 40G
CacheUsage: 1.804 GB (used by oc binary, ISO or cached images)
```
> Issue #2478 Add / as mount point to get the diskUsage for generic driver

- cmd/minishift/cmd/delete.go
- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/stop.go
- cmd/minishift/cmd/util/util.go
@gbraad @amitkrout @agajdosi  following is what we can have as part of stop when using generic driver. In case of other drivers we halt the VM as part of stop but that something we shouldn't do for `generic` but stopping the local OpenShift cluster make sense.
```
$ ./minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.9.0+b8265d6-31)
DiskUsage:  ‘/mnt/?da1’: of df:
CacheUsage: 1.481 GB (used by oc binary, ISO or cached images)
$ ./minishift stop
Stopping local OpenShift cluster...
$ ./minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Stopped
DiskUsage:  ‘/mnt/?da1’: of df:
CacheUsage: 1.481 GB (used by oc binary, ISO or cached images)
```
> Issue #2458 Add stop functionality for generic driver

- cmd/minishift/cmd/start.go
Now it does look like below.
```
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'generic' hypervisor ...
-- Starting Provision Remote Machine ............................ OK
-- OpenShift cluster will be configured with ...
Version: v3.9.0
[...]
```
> Issue #2501 Generic: Fix formatting of start command

- cmd/minishift/cmd/addon/addons_list.go
- pkg/minishift/addon/addon_meta.go
We don't force addon to have url and required openshift version to addon dsl like we have or name and description. So now if an addon contains those details it will be shown in verbose as follow.
```
$ ./minishift addon list --verbose
Name              : admin-user
Description       : Create admin user and assign the cluster-admin role to it.
Url               : 
Openshift Version : >3.9.0
Enabled           : disabled
Priority          : 0
Name              : anyuid
Description       : Changes the default security context constraints to allow pods to run as any user.
Url               : https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines
Openshift Version : 
Enabled           : disabled
Priority          : 0
Name              : che …
```
> Issue #1479 Addon: Add required openshift version and url in verbose list

- pkg/minishift/hostfolder/sshfs_hostfolder.go
@gbraad @anjannath this is now error looks like, I am not sure if cifs also need it.
```
$ ./minishift hostfolder mount test
Note: Make sure that your network and firewall settings on the host allows port 2022 to be opened
error occured while mounting host folder: ssh command error:
command : sudo sshfs docker@192.168.42.1:/home/prkumar/Documents /mnt/sda1/test -o IdentityFile=/home/docker/.ssh/id_rsa -o 'StrictHostKeyChecking=no' -o reconnect -o allow_other -o idmap=none -p 2022
err     : exit status 1
output  : read: Connection reset by peer
```
> Issue #2506 Update error message for sshfs hostfolder mount

- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/util/oc.go
- pkg/minishift/docker/docker.go
This is how now it looks.
```
$ ./minishift start
[...]
Importing 'openshift/origin:v3.9.0' ............. OK
Importing 'openshift/origin-docker-registry:v3.9.0' .. OK
Importing 'openshift/origin-haproxy-router:v3.9.0' .. OK
-- OpenShift cluster will be configured with ...
Version: v3.9.0
-- Pulling the Openshift Container Image. OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ................................
```
> Issue #2469 Break up copy the oc binary and pulling the image

- pkg/minikube/cluster/cluster.go
> Issue #2541 Fix: Proxy env variable to be cleared upon restart

- docs/source/using/addons.adoc
- pkg/minishift/addon/addon_meta.go
How to test
--------------
```
$ cat ~/.minishift/addons/test/test.addon
echo Out of 'FOO'
echo #{FOO}
$ ./minishift addon apply test
-- Applying addon 'test':
Out of 'FOO'
```
> Issue #2464 Addon: Specify empty value for Var-Defaults

- docs/source/using/con_static-ip-overview.adoc
- docs/source/using/experimental-features.adoc
- docs/source/using/static-ip.adoc
Remove the `include` directive. This means we repeat ourselves, but in this instance, that should not be a problem.
**Note:** This is a temporary solution, but since I have not been able to determine the underlying cause, I'm okay with this for the time being.
> Issue #2435: Fix asciidoc error message

- cmd/minishift/cmd/addon/util.go
- cmd/minishift/cmd/openshift/set.go
- cmd/minishift/cmd/openshift/view.go
- pkg/minishift/openshift/openshift.go
- In case of openshift version >= 3.10.x look up path is different.
> Issue #2604 Fix addon apply for different profiles

- pkg/minishift/provisioner/minishift_provisioner.go
How to test
=========
```
$ minishift start --no-provision
$ minishift ip
$ minishift ssh -- sudo systemctl stop docker
$ minishift start --profile test --vm-driver generic --remote-ipaddress <IP> --remote-ssh-user docker  --remote-ssh-key <ssh_key>
```
> Issue #2548 Provisioner: Start docker daemon if not running by default

- pkg/util/github/github.go
> Issue #2625 Removed HOMEBREW_GITHUB_API_TOKEN and GH_TOKEN to access api.github.com

- cmd/minishift/cmd/hostfolder/add.go
- docs/source/using/host-folders.adoc
- pkg/minishift/hostfolder/cifs_hostfolder.go
- pkg/minishift/hostfolder/config/hostfolder_config.go
- pkg/minishift/hostfolder/hostfolder_manager.go
- pkg/minishift/hostfolder/sshfs_hostfolder.go
-  implement `--options` flag for hostfolder add command
Need to test for CIFS and on Windows..
> Issue #2157 pass type specific options for hostfolder add

- docs/source/using/experimental-features.adoc
- docs/source/using/static-ip.adoc
Note: `minishift.exe config set hyperv-virtual-switch` is used in the documentation here instead of **MINISHIFT_HYPERV_VIRTUAL_SWITCH**.
> Issue #2635 Remove Hyper-V fixed IP from experimental, use config

- cmd/minishift/state/instance_dirs.go
The root cause of the issue is that when ~/.minishift/config is not present and user runs `minishift profile set  NON_DEFAULT_PROFILE_NAME` , `createMinishiftDirs(state.InstanceDirs)` only created the directory structure in `~./minishift/profiles`  and not the `~/.minishift/config` . Hence `ensureConfigFileExists(constants.GlobalConfigFile)` gives error as it expects that `~/.minishift/config` would be present.
```
$ tree ~/.minishift
/Users/lmohanty/.minishift
├── cache
│   ├── images
│   ├── iso
│   └── oc
└── profiles
└── Test
├── addons
├── certs
├── config
├── logs
├── machines
└── tmp
```
> Issue #2666 Create directory for global config

- cmd/minishift/cmd/start.go
Fixes #2712 
1.  git revert 6c901e8c31f35d021ee9423312c90b29e0c67040
2.  make clean; make
3. minishift start -> stop-> start
4. echo $?
> Issue #2712 Fixing the exit code for oc context set during restart

- docs/source/using/addons.adoc
- pkg/minishift/addon/addon_meta.go
- pkg/minishift/addon/manager/addon_manager.go
Fixes: #650 
Define an add-on as follows in `test-addon/test-addon.addon`
```
echo "Minishift"
```
```
$ minishift addons install ~/test-addon/
Add-on installation failed with the error: The add-on depends on: [test, demo-addon]. Please install these first.
```
> Issue #650 add add-on metadata to express dependencies

- cmd/minishift/cmd/openshift/list_versions.go
- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_preflight.go
- cmd/minishift/cmd/util/util.go
- pkg/minishift/openshift/openshift.go
- pkg/minishift/openshift/version/openshift_versions.go
- pkg/minishift/openshift/version/openshift_versions_test.go
- test/integration/features/provision-various-versions.feature
Fix #2624 
```
$ minishift start --openshift-version latest
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0-rc.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0-rc.0' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
Checking driver binary is executable ... OK
[...]
-- OpenShift cluster will be configured with ...
Version: v3.10.0-rc.0
-- Pulling the Openshift Container Image ................ OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting …
```
> Issue #2624 Support 'latest' tag in openshift-version flag

- cmd/minishift/cmd/hostfolder/add.go
- cmd/minishift/cmd/hostfolder/add_test.go
Fixes #2716 
1. `minishift hostfolder add --type sshfs --source /tmp/foo --target /mnt/sda1/foo " "`
> Issue #2716 show usage if hostfolder name is empty

- pkg/minishift/addon/manager/addon_manager.go
- pkg/minishift/openshift/version/openshift_versions.go
- pkg/minishift/openshift/version/openshift_versions_test.go
- pkg/util/utils.go
- pkg/util/utils_test.go
Fixes #2732 
1. cat demoaddon.adon
```
echo "Hello world"
```
Now, install and apply.
Note: Expect error here.
2. Update ~/.minishift/addons/demoaddon/demoaddon.addon
```
echo "Hello world"
```
Note: Apply should work.
> Issue #2732 Use semver comparisons instead via util.VersionOrdinal

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/config/set.go
- cmd/minishift/cmd/config/set_test.go
- cmd/minishift/cmd/start.go
- test/integration/features/cmd-config.feature
- start => stop => start user don't need to remember start flags.
How to test
---------------
```
$ minishift start --vm-driver virtualbox --memory 4GB --cpu 5
$ minishift stop
$ minishift start => this will still be going to start with what user provided the first time
```
> Issue #2611 Populate start flags to viper config

- Makefile
- docs/source/contributing/developing.adoc
- test/integration/features/addons/addon-registry-route.feature
- test/integration/features/addons/addon-xpaas.feature
- test/integration/features/addons/cmd-addons.feature
- test/integration/features/basic.feature
- test/integration/features/cmd-config.feature
- test/integration/features/cmd-docker-env.feature
- test/integration/features/cmd-image.feature
- test/integration/features/cmd-oc-env.feature
- test/integration/features/cmd-openshift.feature
- test/integration/features/cmd-profile.feature
- test/integration/features/cmd-version.feature
- test/integration/features/experimental-flags.feature
- test/integration/features/flags.feature
- test/integration/features/generic-driver.feature
- test/integration/features/provision-various-versions.feature
- test/integration/features/proxy.feature
- test/integration/features/stories/coolstore.feature
Fixes #2720 
2. Moves basic.feature and coolstore.feature into directory `stories`
3. Moves addon related features into directory `addons`
4. Adds tag `@quick` to scenarios which does not require a `minishift start` + to elementary.feature
5. Adds tag `@core` to most of the features, except the specialized ones like xpaas.feature. This tags server to PR checks
6. Adds tag `@disabled` to features proxy and coolstore. Any feature, scenario or step tagged as `disabled` will not be run.
1. run `make integration` - would be quick test containing 184 scenarios and only 1 minishift start
2. run `make integration_pr` - would run all the tests except some more specialized, for example addon-xpaas.feature containing several app deployments. Usable during PR checks.
3. …
> Issue #2720 Separate tests into core and extra to be run in CI

- cmd/minishift/cmd/util/oc.go
- pkg/minishift/constants/constants.go
Fixes #2768 
1. minishift start
2. docker images => this contain origin-cli image instead origin one for v3.10 and origin for v3.9
> Issue #2768 Use origin-cli image if openshift >= 3.10.x

- addons/htpasswd-identity-provider/htpasswd-identity-provider.addon
- addons/htpasswd-identity-provider/htpasswd-identity-provider.addon.remove
Fixes  #2742 
1. Use this PR and apply htpasswd-identity-provider
2. Go to web console and try to login with different user => this should fail.
3. login with same user with the password you provide during the apply of the addon (default: developer) => should successful.
> Issue #2742 Change to htpasswd addon for v3.10

- test/integration/che/che-steps.go
- test/integration/che/che.go
- test/integration/che/cheAPI.go
- test/integration/features/addons/addon-che.feature
- test/integration/integration_test.go
Fix #2657.
Moves Che tests from minishift-addons repository here. It keeps them in separate package `Che` to isolate them from the more default steps focused clearly on usage of Minishift. 
How to test:
- `make integration GODOG_OPTS=-tags=addon-che`
> Issue #2657 Move Che add-on tests to Minishift repository

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/start.go
- docs/source/using/basic-usage.adoc
Fixes #2792
1. ./minishift start --cpus 3 --memory 6GB
2. ./minishift config view => this will contain cpus and memory value
3. ./minishift config set save-start-flags false
4. ./minishift unset cpus
5. ./minishift unset memory
6. ./minishift start --cpus 3 --memory 6GB
7. ./minishift config view => this will now not keep record of start flags.
> Issue #2792 Add save-start-flags bool option to config

- cmd/minishift/cmd/ip.go
- test/integration/features/cmd-profile.feature
Fixes #2163
1. ./minishift ip
Running this command requires an existing 'minishift' VM, but no VM is defined.
> Issue #2163 Fix minishift ip command in case instance doesn't exist

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/openshift/component_add.go
- cmd/minishift/cmd/start.go
- pkg/minishift/clusterup/clusterup.go
- pkg/minishift/constants/constants.go
- test/integration/features/basic.feature
Fixes #2789 
1. minishift start --v=5 should shows
Running 'oc' with: 'cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.10.0' ...
2. minishift start --openshift-version 3.9.0 should also success but not use the `--image` option
3. image option should not be listed in the start flag.
4. After minishift start => minishift ssh -- docker images => contain all the images with same tag.
> Issue #2789 use specific version of image for cluster up

- pkg/minishift/docker/image/image.go
- test/integration/features/cmd-image.feature
Fixes #2717 
1.  `minishift start` => this should now cache the `origin-control-plane` image.
2.  `minishif delete`
3.  `minishift start` => this should consume the `origin-control-plane` image.
> Issue #2717 cache origin-control-plane image if openshift >= 3.10

- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_test.go
- test/integration/features/proxy.feature
Fixes #2759
1. minishift start --http-proxy <proxy_uri> => should now works for 3.10
> Issue #2759 Add docker subnet as NO_PROX for openshift >= 3.10

- cmd/minishift/cmd/logs.go
- pkg/minikube/cluster/cluster.go
- pkg/minikube/cluster/cluster_test.go
Fix #2555 
**Steps to Test**
- `make` to get binary from this PR
- `minishift start`
- `minishift logs -t 10` or `minishift logs --tail 10`.
**Testing Scenarios**
- `minishift logs`
- `minishift logs -f`
- `minishift logs -t 10` or some number you like
- `minishift logs -t 10 -f`
> Issue #2555 Add tail option for minishift logs

- Makefile
- centos_ci.sh
- docs/source/contributing/releasing.adoc
Fixes #2850 
1. Change in the Makefile set `SKIP_INTEGRATION_TEST` value as `true`
2. run `make ci_release` should not execute the `integration tests`
> Issue #2850 Add a way to skip integration test for release

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/timezone.go
- docs/source/using/experimental-features.adoc
- pkg/minikube/constants/constants.go
- pkg/minishift/config/instance_state_config.go
- pkg/minishift/config/validations.go
- pkg/minishift/config/validations_test.go
- pkg/minishift/timezone/timezone.go
- test/integration/features/basic.feature
Fixes #2854 
```
$ minishift start 
$ minishift timezone
Local time: Fri 2018-10-05 08:55:35 EDT
Universal time: Fri 2018-10-05 12:55:35 UTC
RTC time: Fri 2018-10-05 12:55:33
Time zone: America/New_York (EDT, -0400)
NTP enabled: n/a
NTP synchronized: no
RTC in local TZ: no
DST active: yes
Last DST change: DST began at
Sun 2018-03-11 01:59:59 EST
Sun 2018-03-11 03:00:00 EDT
Next DST change: DST ends (the clock jumps one hour backwards) at
Sun 2018-11-04 01:59:59 EDT
Sun 2018-11-04 01:00:00 EST
$ minishift delete
$ minishift start --timezone Asia/Kolkata
$ ./minishift ssh -- sudo timedatectl status
Local time: Fri 2018-10-05 18:47:27 IST
Universal time: Fri 2018-10-05 13:17:27 UTC
RTC time: Fri 2018-10-05 13:17:24
Time zone: Asia/Kolkata (IST, +0530)
NTP …
```
> Issue #2854 Add timezone flag to start and a timezone command

- test/integration/features/addons/addon-registry-route.feature
- test/integration/features/cmd-docker-env.feature
- test/integration/features/cmd-oc-env.feature
- test/integration/testsuite/minishift.go
- test/integration/testsuite/testsuite.go
- test/integration/util/scenario_variables.go
- test/integration/util/shell.go
Fixes #2355 
Steps to test the pull request:
1. make integration MINISHIFT_BINARY=/home/agajdosi/minishift/minishift GODOG_OPTS=-tags=addon-registry-route
Changes in the PR:
- replaced checks using `curl`
- replaced steps using backticks
- moved scenario variables functionality to `util` package of integration tests
- added scenario variables functionality to steps executing commands in shell instance
> Issue #2355 Steps in addon-registry-route.feature doesn't work in cmd

- pkg/minikube/cluster/cluster.go
- test/integration/testsuite/minishift.go
- test/integration/testsuite/testsuite.go
The url with /console should work with previous versions also.
Fixes #2892 
1.  `$ minishift  console ` should point to `https://Minishift IP:8443/console` instead of `https://IP:8443`
Same goes for 
1. minishift console --machine-readable
1. minishift console --url
> Issue #2892 Changing webconsole URL for OpenShift 3.11

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/ip.go
- cmd/minishift/cmd/start.go
- docs/source/using/experimental-features.adoc
- docs/source/using/static-ip.adoc
- pkg/minishift/network/settings.go
- pkg/minishift/network/settings_windows.go
Fixes #2629 
```
$ minishift start 
-- Writing current configuration for static assignment of IP address ... OK => on supported platform
-- Writing current configuration for static assignment of IP address ... FAIL => on unsupported platform or in case any othere issue.
$ minishift ssh -- cat /var/lib/minishift/networking-eth0  => should be present with required data.
```
> Issue #2629 set static ip after minishift instance start

- Makefile
> Issue #2922 Update centos iso from 1.12.0 to 1.13.0

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/start.go
Fixes #2933 
1. Disable HyperV
2. Restart as prompted
3. minishift start --vm-driver virtualbox
> Issue #2933 HypervVirtualSwitch flag default value should be set in start.go

- cmd/minishift/cmd/util/oc.go
Fixes #2949 
Corrects typo in cmd/minishift/cmd/util/oc.go
> Issue #2949 Fixed typo in cmd/minishift/cmd/util/oc.go

- docs/source/using/experimental-features.adoc
Fix #2938.
With ' in option value minishift fails to start with error
```
Starting OpenShift cluster -- Extra 'oc' cluster up flags (experimental) ...
'--enable=*,service-catalog''
.Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --routing-suffix 192.168.42.250.nip.io --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.42.250 --enable=*,service-catalog'
err     : exit status 1
output  : bash: -c: line 0: unexpected EOF while looking for matching `''
bash: -c: line 1: syntax error: unexpected end of file
```
> Remove ' from --enable option value

- test/integration/features/addons/addon-che-with-anyuid.feature
- test/integration/features/addons/addon-che.feature
Fixes #2964
1. make integration GODOG_OPTS="-tags addon-che,addon-che-with-anyuid"
2. 
3. 
4.
> Issue #2964 Disable Java CentOS stack in Che feature file

- .codecov.yml
- .travis.yml
- Makefile
- docs/source/contributing/developing.adoc
Fixes #2819
1. you can see it working on my fork: https://codecov.io/gh/agajdosi/minishift and https://travis-ci.org/agajdosi/minishift
2. as admin of Minishift project you can enable Minishift project in codecov.io and then next build of this PR would probably upload the report
> Issue #2819 Add codecov.io into make tests and Travis

- addons/registry-route/registry-route.addon
Fixes #2907 
```console
$ minishift delete
-- make sure you take artifact from PR locally --
$ minishift start
$ minishift addon install --defaults
$ minishift addon apply registry-route
```
Now follow the steps on the provided issue #2907
> Issue #2907 Update registry route addon to use passthrough route instead edge

- docs/source/getting-started/setting-up-virtualization-environment.adoc
Ubuntu-18.10-specific configuration notes added.
Fixes #2970
1. Install minishift on Ubuntu/Xubuntu 18.10, follow Setting up virtualization 18.10-specific notes.
> Ubuntu-18.10-specific configuration notes added

- .circleci/config.yml
- Makefile
- docs/source/contributing/releasing.adoc
We need to setup an env variable `GITHUB_TOKEN` in circle CI to upload the bits, 
and also we'll need a circle ci token to trigger the job.
> Issue #2837 release job in circle ci for minishift with systemtray bits

- pkg/minishift/systemtray/minishifttray.go
Fixes #3002 
/cc @amitkrout @agajdosi Could you guys verify if this fixes the issue both in windows 7 and 10
> Issue #3002 pass VBOX_MSI_INSTALL_PATH env to systray process

- cmd/minishift/cmd/start.go
Fixes: #3037 
Here's the artefacts for [darwin](https://5673-62728051-gh.circle-artifacts.com/0/ms/darwin-amd64/systemtray/minishift) and [windows](https://5673-62728051-gh.circle-artifacts.com/0/ms/windows-amd64/systemtray/minishift.exe)
/cc @amitkrout
> Issue #3037 Check config value before starting systemtray

- cmd/minishift/cmd/addon/addon_apply.go
- cmd/minishift/cmd/addon/addon_remove.go
- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/openshift/start.go
- cmd/minishift/cmd/root.go
- cmd/minishift/cmd/start.go
- cmd/minishift/cmd/start_test.go
- cmd/minishift/cmd/update.go
- cmd/minishift/cmd/util/shared_flags.go
- cmd/minishift/cmd/util/util.go
- pkg/minishift/constants/constants.go
Fixes #2900 
```
$ export MINISHIFT_ENABLE_EXPERIMENTAL=y
$ minishift start --write-config
$ minishift openshift start
```
> Issue #2900 add write-config flag and cluster start

- cmd/minishift/cmd/setup.go
- pkg/minishift/setup/hypervisor/virtualization_darwin.go
Fixes #2840 
1. On a clean mac (without prerequisite of minishift set)
2.  `minishift start` ==> this will fail
3.  `minishift setup` ==> error msg saying to run command with sudo
4.  `sudo minishift setup`
> Issue #2840 Add macOS support to setup command

- addons/admissions-webhook/admissions-webhook.addon
- addons/admissions-webhook/patch.json
- cmd/minishift/cmd/util/util.go
- docs/source/using/addons.adoc
- pkg/minishift/addon/manager/addon_manager_test.go
- test/integration/features/addons/cmd-addons.feature
- test/integration/features/basic.feature
2. `minishift addons install --defaults`
3.  `minishift addons apply admissions-webhook`
4.  `minishift openshift config view --target kube`
> Issue #2676 Addon for enabling mutating and admission webhooks

- Makefile
- docs/Rakefile
- docs/source/_topic_map.yml
- docs/source/troubleshooting/troubleshooting-misc.adoc
- docs/source/using/basic-usage.adoc
- docs/source/using/choosing-iso-image.adoc
- docs/source/using/host-folders.adoc
- docs/source/using/index.adoc
- docs/source/using/static-ip.adoc
Fixes #3053.
This also removes references to the Minikube ISO.
> Issue #3053 Remove Boot2Docker from documentation

- pkg/minishift/config/allinstancesconfig.go
- pkg/minishift/config/instance_config.go
- pkg/minishift/config/instance_state_config.go
edit `allinstances.json` and put in an erroneous character.
> Issue #3091 Fail when json configuration is invalid

- docs/source/contributing/developing.adoc
Fixes #3139 
**Note:** Originally, I had intended to include steps for installing Make, but we currently do not have such instructions for Git or a recent Go distribution. For this reason, I assume that we expect developers to know how to install the prerequisites.
> Issue #3139 Add Make to development prerequisites

- docs/source/contributing/developing.adoc
Fixes #3159.
**Note:** The list of binaries that can be executed from **_out/_** (at line 171 of **_contributing/developing.adoc_** in this PR) remains intentionally unchanged due to the fact that cross-compilation was already mentioned.
> Issue #3159 Remove Windows as documented build environment

- test/integration/features/cmd-openshift.feature
- test/integration/util/util.go
Fixes #3171 
1. `make integration GODOG_OPTS=-tags=basic`
I've tested the PR on Windows 7 and 10 and Fedora, works fine.
> Issue #3171 Tests fail to get status of container in older PS/cmd

- addons/xpaas/v3.10/xpaas-streams/fis-image-streams.json
- addons/xpaas/v3.11/xpaas-streams/fis-image-streams.json
it allows to have them listed in catalog component types when using odo
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
Fixes #3193
1. minishift start
2. install odo >= 0.19.0
3. odo catalog component list
4. the Fuse images should be listed
> Remove hidden tag for latest Fuse images #3193

- docs/source/getting-started/setting-up-virtualization-environment.adoc
I tried using minishift with hyperkit and the existing documentation was unclear on which dependencies were provided by having Docker Mac installed. I reorganized that section a little to make it clear that there are two parts and that both of them can be satisfied from Homebrew but Docker Mac users only need docker-machine-driver-hyperkit.
> Update instructions for using hyperkit

- cmd/minishift/cmd/console.go
Fixes #3203 
2. `minishift console --request-oauth-token`
3. In the browser after logging in, you should see the token
> Issue #3203 Fix oauth token request token uri in console command

- addons/che/che.addon
Update Che addon default parameter value that sets Che plugin registry location.
It was changed recently and no longer compatible with the old value of the parameter.
1.  Start minishift
2. Enable Che addon
3. Create Che 7 workspace
4. Start Che 7 workspace
> Update Che addon default parameter value

- addons/che/templates/che-server-template.yaml
The minishift addon uses hardcoded 7.1.0 Che Image, it's why we still need to set deprecated in 7.4.0 `CHE_INFRA_OPENSHIFT_PROJECT` configuration env var
Fixes https://github.com/minishift/minishift/issues/3401 and should fix https://github.com/eclipse/che/issues/15380 as well
1. Apply Che minishift addon
2. Open Che in browser
3. Create any workspace
4. Try to start it
> Set CHE_INFRA_OPENSHIFT_PROJECT for backward compatibility

- cmd/minishift/cmd/config/config.go
- cmd/minishift/cmd/start_preflight.go
- pkg/minishift/setup/hypervisor/virtualization_darwin.go
Downloads hyperkit binary from
github.com/code-ready/machine-driver-hyperkit/releases
Fixes #3430 
1. remove any previous installation of hyperkit and the hyperkit driver
(` rm -rf $(which hyperkit) $(which docker-machine-driver-hyperkit)`)
2. `minishift start` should fail
3. `sudo minishift setup`
4. `minishift start` should succeed now
> Issue #3430 Install hyperkit when setup command is ran

- docs/source/getting-started/installing.adoc
You no longer need to use `--cask` and to save other warnings you can add `--no-quarantine`
> Documentation Only - Homebrew Mac Steps
